create type scheduler.goal_type as enum ('EDSL', 'JAR');

alter table scheduler.scheduling_goal_definition
  add column type scheduler.goal_type not null default 'EDSL',
  add column uploaded_jar_id integer,
  add column parameter_schema jsonb,

  alter column definition drop not null,

  add constraint scheduling_procedure_has_uploaded_jar
    foreign key (uploaded_jar_id)
    references merlin.uploaded_file
    on update cascade
    on delete restrict,

  add constraint check_goal_definition_type_consistency
    check (
    (type = 'EDSL' and definition is not null and uploaded_jar_id is null)
    or
    (type = 'JAR' and uploaded_jar_id is not null and definition is null)
    );

comment on column scheduler.scheduling_goal_definition.type is e''
  'The type of this goal definition, "EDSL" or "JAR".';
comment on column scheduler.scheduling_goal_definition.definition is e''
  'An executable expression in the Merlin scheduling language.'
  'Should be non-null when type is EDSL';
comment on column scheduler.scheduling_goal_definition.uploaded_jar_id is e''
  'The foreign key to the uploaded_file entry containing the procedure jar'
  'Should be non-null when type is JAR';
comment on column scheduler.scheduling_goal_definition.parameter_schema is e''
  'The schema for parameters that can be passed to goal instances using this definition.'
  'Similar schema to parameter_set''s in Merlin.';

alter table scheduler.scheduling_specification_goals
  add column goal_invocation_id integer generated by default as identity,
  add column arguments jsonb not null default '{}'::jsonb,

  drop constraint scheduling_specification_goals_primary_key,
  add constraint scheduling_specification_goals_primary_key
    primary key (goal_invocation_id);

comment on column scheduler.scheduling_specification_goals.goal_invocation_id is e''
  'The id of a specific goal invocation in the specification. Primary key.';
comment on column scheduler.scheduling_specification_goals.arguments is e''
  'The arguments that will be passed to this goal when invoked.'
  'Follows scheduler.scheduling_goal_definition.parameter_schema.'
  'Only valid for procedural goals.';

-- update goal_analysis PK
alter table scheduler.scheduling_goal_analysis
  add column goal_invocation_id integer null, -- temp set as nullable so we can insert, made not null by PK constraint below
  add column arguments jsonb not null default '{}'::jsonb,

  drop constraint scheduling_goal_analysis_primary_key;

comment on column scheduler.scheduling_goal_analysis.goal_invocation_id is e''
  'The associated goal invocation ID.';
comment on column scheduler.scheduling_goal_analysis.arguments is e''
  'The "as run" arguments passed to this goal during the scheduling run.'
  'Follows scheduler.scheduling_goal_definition.parameter_schema.';

update scheduler.scheduling_goal_analysis as sga
set goal_invocation_id = ssg.goal_invocation_id
from scheduler.scheduling_request as sr
  join scheduler.scheduling_specification_goals as ssg
  on sr.specification_id = ssg.specification_id
where sr.analysis_id = sga.analysis_id
  and sga.goal_id = ssg.goal_id;

alter table scheduler.scheduling_goal_analysis
  add constraint scheduling_goal_analysis_primary_key
    primary key (analysis_id, goal_invocation_id);

-- update created_activities PK
alter table scheduler.scheduling_goal_analysis_created_activities
  drop constraint created_activities_primary_key,
  -- temp set as nullable so we can insert, made not null by PK constraint below
  add column goal_invocation_id integer null;

comment on column scheduler.scheduling_goal_analysis_created_activities.goal_invocation_id is e''
  'The associated goal invocation ID from the scheduling specification.';

update scheduler.scheduling_goal_analysis_created_activities as sgaca
set goal_invocation_id = ssg.goal_invocation_id
from scheduler.scheduling_request as sr
       join scheduler.scheduling_specification_goals as ssg
            on sr.specification_id = ssg.specification_id
where sr.analysis_id = sgaca.analysis_id
  and sgaca.goal_id = ssg.goal_id;

alter table scheduler.scheduling_goal_analysis_created_activities
  drop column goal_id,
  drop column goal_revision,

  add constraint created_activities_primary_key
    primary key (analysis_id, goal_invocation_id, activity_id),
  add constraint created_activities_references_scheduling_goal_analysis
    foreign key (analysis_id, goal_invocation_id)
      references scheduler.scheduling_goal_analysis
      on update cascade
      on delete cascade;

-- update satisfing_activities PK
alter table scheduler.scheduling_goal_analysis_satisfying_activities
  drop constraint satisfying_activities_primary_key,
  -- temp set as nullable so we can insert, made not null by PK constraint below
  add column goal_invocation_id integer null;

comment on column scheduler.scheduling_goal_analysis_satisfying_activities.goal_invocation_id is e''
  'The associated goal invocation ID from the scheduling specification.';

update scheduler.scheduling_goal_analysis_satisfying_activities as sgasa
set goal_invocation_id = ssg.goal_invocation_id
from scheduler.scheduling_request as sr
       join scheduler.scheduling_specification_goals as ssg
            on sr.specification_id = ssg.specification_id
where sr.analysis_id = sgasa.analysis_id
  and sgasa.goal_id = ssg.goal_id;

alter table scheduler.scheduling_goal_analysis_satisfying_activities
  drop column goal_id,
  drop column goal_revision,

  add constraint satisfying_activities_primary_key
    primary key (analysis_id, goal_invocation_id, activity_id),
  add constraint satisfying_activities_references_scheduling_goal_analysis
    foreign key (analysis_id, goal_invocation_id)
      references scheduler.scheduling_goal_analysis
      on update cascade
      on delete cascade;

call migrations.mark_migration_applied('8');
