create type scheduler.goal_type as enum ('EDSL', 'JAR');

alter table scheduler.scheduling_goal_definition
  add column type scheduler.goal_type not null default 'EDSL',
  add column uploaded_jar_id integer,
  add column parameter_schema jsonb,

  alter column definition drop not null,

  add constraint scheduling_procedure_has_uploaded_jar
    foreign key (uploaded_jar_id)
    references merlin.uploaded_file
    on update cascade
    on delete restrict,

  add constraint check_goal_definition_type_consistency
    check (
    (type = 'EDSL' and definition is not null and uploaded_jar_id is null)
    or
    (type = 'JAR' and uploaded_jar_id is not null and definition is null)
    );

alter table scheduler.scheduling_specification_goals
  add column goal_invocation_id integer generated by default as identity,
  add column arguments jsonb not null default '{}'::jsonb,

  drop constraint scheduling_specification_goals_primary_key,
  add constraint scheduling_specification_goals_primary_key
    primary key (goal_invocation_id);

-- update goal_analysis PK
alter table scheduler.scheduling_goal_analysis
  add column goal_invocation_id integer null, -- temp set as nullable so we can insert, made not null by PK constraint below
  add column arguments jsonb not null default '{}'::jsonb,

  drop constraint scheduling_goal_analysis_primary_key;

update scheduler.scheduling_goal_analysis as sga
set goal_invocation_id = ssg.goal_invocation_id
from scheduler.scheduling_request as sr
  join scheduler.scheduling_specification_goals as ssg
  on sr.specification_id = ssg.specification_id
where sr.analysis_id = sga.analysis_id
  and sga.goal_id = ssg.goal_id;

alter table scheduler.scheduling_goal_analysis
  add constraint scheduling_goal_analysis_primary_key
    primary key (analysis_id, goal_invocation_id);

-- update created_activities PK
alter table scheduler.scheduling_goal_analysis_created_activities
  drop constraint created_activities_primary_key,
  -- temp set as nullable so we can insert, made not null by PK constraint below
  add column goal_invocation_id integer null;

update scheduler.scheduling_goal_analysis_created_activities as sgaca
set goal_invocation_id = ssg.goal_invocation_id
from scheduler.scheduling_request as sr
       join scheduler.scheduling_specification_goals as ssg
            on sr.specification_id = ssg.specification_id
where sr.analysis_id = sgaca.analysis_id
  and sgaca.goal_id = ssg.goal_id;

alter table scheduler.scheduling_goal_analysis_created_activities
  drop column goal_id,
  drop column goal_revision,

  add constraint created_activities_primary_key
    primary key (analysis_id, goal_invocation_id, activity_id);

-- update satisfing_activities PK
alter table scheduler.scheduling_goal_analysis_satisfying_activities
  drop constraint satisfying_activities_primary_key,
  -- temp set as nullable so we can insert, made not null by PK constraint below
  add column goal_invocation_id integer null;

update scheduler.scheduling_goal_analysis_satisfying_activities as sgasa
set goal_invocation_id = ssg.goal_invocation_id
from scheduler.scheduling_request as sr
       join scheduler.scheduling_specification_goals as ssg
            on sr.specification_id = ssg.specification_id
where sr.analysis_id = sgasa.analysis_id
  and sgasa.goal_id = ssg.goal_id;

alter table scheduler.scheduling_goal_analysis_satisfying_activities
  drop column goal_id,
  drop column goal_revision,

  add constraint satisfying_activities_primary_key
    primary key (analysis_id, goal_invocation_id, activity_id);

call migrations.mark_migration_applied('8');
