create type anchor_type as enum ('activity', 'event', 'plan');

/*
 Insert the following columns onto activity directive

  anchor_type anchor_type not null default 'plan',
  anchored_to_start boolean not null default true,
  anchor_id integer not null default plan_id,
  is_event boolean not null default false,
*/

-- if events have duration, it should be known without simulation
-- would need a duration column
-- can we have non-fixed duration events?
-- if events are simulatable, then the only current known difference is how the UI renders them

drop schema hasura_functions cascade;

alter table activity_directive
  add column anchor_type anchor_type not null default 'plan',
  add column anchored_to_start boolean not null default true,
  add column anchor_id integer;

update activity_directive
set anchor_id = plan_id
where activity_directive.anchor_id is null;

-- Defaults are filled in before before triggers (per statement)
-- Before triggers run before immediate constraints (per statement)
-- Immediate constraints are checked before after triggers (per statement)
-- After triggers run as the final check per statement
-- Deferred Constraints run at the end of the transaction
insert into activity_directive (plan_id, start_offset, type, arguments) values (1, '0 years 0 mons 0 days 163 hours 40 mins 22.844 secs', 'BiteBanana', '{}');


create table event_directive(
                              id integer
                                generated by default as identity,
                              plan_id integer
                                references plan
                                  on update cascade
                                  on delete cascade,

                              name text,
                              tags text[] default '{}',

                              primary key (id, plan_id)
);

create table anchor(
  id integer
    generated by default as identity
    primary key,
  anchor_type anchor_type
                                               not null,
                     anchee_type anchor_type
                                               not null
                       check(anchee_type != 'plan'),
                     anchored_to_start boolean not null default true,
                     anchor_id integer,
                     anchee_id integer,
                     anchee_plan_id integer
)
