
package spice.tspice;


import java.io.*;
import java.util.*;
import spice.basic.*;
import spice.testutils.JNITestutils;
import spice.testutils.Testutils;
import static spice.basic.AngularUnits.*;

/**
Class TestPlanetographicCoordinates provides methods that implement
test families for the class PlanetographicCoordinates.

<p>Version 1.0.0 23-NOV-2009 (NJB)
*/
public class TestPlanetographicCoordinates extends Object
{

   //
   // Class constants
   //


   //
   // Class variables
   //


   //
   // Methods
   //

   /**
   Test PlanetographicCoordinates and associated classes.
   */
   public static boolean f_PlanetographicCoordinates()

      throws SpiceException
   {
      //
      // Constants
      //
      final String                      PCK       = "test.tpc";

      final double                      TIGHT_TOL = 1.e-12;
      final double                      SQ3       = Math.sqrt(3.0);

      //
      // Local variables
      //
      Body                              Earth = new Body( 399    );
      Body                              Moon  = new Body( "moon" );

      PlanetographicCoordinates         pgr;
      PlanetographicCoordinates         pgr2;

      Matrix33                          jac1;
      Matrix33                          jac2;
      Matrix33                          invmat;

      Vector3                           pos;
      Vector3                           xPos;

      boolean                           ok;

      double                            altitude;
      double                            dist;
      double                            f;
      double                            latitude;
      double                            longitude;
      double[]                          radii;
      double                            re;
      double                            rp;
      double                            xAltitude;
      double                            xLatitude;
      double                            xLongitude;


      //
      //  We enclose all tests in a try/catch block in order to
      //  facilitate handling unexpected exceptions.  Unexpected
      //  exceptions are trapped by the catch block at the end of
      //  the routine; expected exceptions are handled locally by
      //  catch blocks associated with error handling test cases.
      //
      //  Therefore, JNISpice calls that are expected to succeed don't
      //  have any subsequent "chckxc" type calls following them, nor
      //  are they wrapped in in try/catch blocks.
      //
      //  Expected exceptions that are *not* thrown are tested
      //  via a call to {@link spice.testutils.Testutils#dogDidNotBark}.
      //

      try
      {

         JNITestutils.topen ( "f_PlanetographicCoordinates" );


         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "Setup: create and load kernels." );


         //
         // Clear the KernelDatabase system.
         //
         KernelDatabase.clear();

         JNITestutils.tstlsk();

         //
         // Delete PCK if it exists. Create and load a PCK file.
         //
         ( new File ( PCK ) ).delete();

         JNITestutils.tstpck( PCK, true, false );



         // ***********************************************************
         //
         //    Error cases
         //
         // ***********************************************************


         //
         // We don't need to test every exception that can occur, but
         // we must:
         //
         //    - Test every exception generated in the Java API layer.
         //
         //    - Test at least one exception generated by CSPICE for
         //      every CSPICE class wrapper.
         //

         //
         // --------Case-----------------------------------------------
         //
         JNITestutils.tcase (  "Error: negative re in rectangular to " +
                               "planetographic lon/lat-based constructor " +
                               "call. "   );

         try
         {
            re  = -1.e4;
            f   =  0.1;

            longitude = 2.0;
            latitude  = 0.5;
            altitude  = 1.e3;

            pgr = new PlanetographicCoordinates( Earth, longitude, latitude,
                                                             altitude, re, f );

            //
            // If an exception is *not* thrown, we'll hit this call.
            //

            Testutils.dogDidNotBark (  "SPICE(VALUEOUTOFRANGE)" );

         }
         catch ( SpiceException ex )
         {
            ok = JNITestutils.chckth ( true, "SPICE(VALUEOUTOFRANGE)", ex );

            if ( !ok )
            {
               //
               // For debugging
               //ex.printStackTrace();
            }
         }


         //
         // --------Case-----------------------------------------------
         //
         JNITestutils.tcase (  "Error: negative re in rectangular to " +
                               "planetographic vector-based constructor " +
                               "call. "   );

         try
         {
            re   =  -1.e4;
            f    =  0.1;

            pos  = new Vector3( 1.e4, 1.5e4, 7.e3 );

            pgr = new PlanetographicCoordinates( Moon, pos, re, f );

            //
            // If an exception is *not* thrown, we'll hit this call.
            //

            Testutils.dogDidNotBark (  "SPICE(VALUEOUTOFRANGE)" );

         }
         catch ( SpiceException ex )
         {
            ok = JNITestutils.chckth ( true,   "SPICE(VALUEOUTOFRANGE)", ex );
         }

         //
         // --------Case-----------------------------------------------
         //
         JNITestutils.tcase (  "Error: negative re in rectangular to " +
                               "planetographic vector-based Jacobian call. " );

         try
         {
            re   =  -1.e4;
            f    =  0.1;

            pos  = new Vector3( 1.e4, 1.5e4, 7.e3 );

            jac1 = PlanetographicCoordinates.getRecPgrJacobian( Earth, pos,
                                                                       re, f );

            //
            // If an exception is *not* thrown, we'll hit this call.
            //

            Testutils.dogDidNotBark (  "SPICE(VALUEOUTOFRANGE)" );

         }
         catch ( SpiceException ex )
         {
            ok = JNITestutils.chckth ( true,   "SPICE(VALUEOUTOFRANGE)", ex );
         }



         //
         // --------Case-----------------------------------------------
         //
         JNITestutils.tcase (  "Error: f > 1 in " +
                               "planetographic constructor call. " );

         try
         {
            re  =  1.e4;
            f   =  1.1;

            pos = new Vector3( 1.e4, 1.5e4, 7.e3 );

            pgr = new PlanetographicCoordinates( Moon, pos, re, f );

            //
            // If an exception is *not* thrown, we'll hit this call.
            //

            Testutils.dogDidNotBark (  "SPICE(VALUEOUTOFRANGE)" );

         }
         catch ( SpiceException ex )
         {
            ok = JNITestutils.chckth ( true,   "SPICE(VALUEOUTOFRANGE)", ex );
         }






         // ***********************************************************
         //
         //    Normal cases
         //
         // ***********************************************************


         //
         // Constructor tests:
         //


         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "Construct planetographic coordinates for a " +
                              "surface point on the unit sphere. Use " +
                              "scalar planetographic coordinate " +
                              "constructor." );

         re        = 1.0;
         f         = 0.0;

         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         altitude  =  0.0;

         pgr = new PlanetographicCoordinates( Earth, longitude, latitude,
                                                             altitude, re, f );

         pos = pgr.toRectangular();

         ok  = JNITestutils.chcksd ( "X coordinate",
                                     pos.toArray()[0],
                                     "~",
                                     SQ3/4,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "Y coordinate",
                                     pos.toArray()[1],
                                     "~",
                                     0.25,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "Z coordinate",
                                     pos.toArray()[2],
                                     "~",
                                     SQ3/2,
                                     TIGHT_TOL          );



         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "Construct planetographic coordinates for " +
                              "a surface point on the Earth.  Use scalar " +
                              "planetographic coordinate constructor."       );


         re        = 6378.14;
         rp        = 6356.75;
         f         = ( re - rp ) / re;

         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         altitude  = 10.0;

         pgr = new PlanetographicCoordinates( Earth, longitude, latitude,
                                                             altitude, re, f );



         ok  = JNITestutils.chcksd ( "longitude",
                                     pgr.getLongitude(),
                                     "~",
                                     longitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "latitude",
                                     pgr.getLatitude(),
                                     "~",
                                     latitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "altitude",
                                     pgr.getAltitude(),
                                     "~",
                                     altitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "RE",
                                     pgr.getEquatorialRadius(),
                                     "~",
                                     re,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "F",
                                     pgr.getFlatteningCoefficient(),
                                     "~",
                                     f,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksi ( "Body",
                                     pgr.getBody().getIDCode(),
                                     "=",
                                     399,
                                     0                         );

         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "Test copy constructor." );

         re        = 6378.14;
         rp        = 6356.75;
         f         = ( re - rp ) / re;

         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         altitude  = 10.0;

         pgr = new PlanetographicCoordinates( Earth, longitude, latitude,
                                                             altitude, re, f );


         pgr2 = new PlanetographicCoordinates( pgr );

         //
         // Change pgr; make sure pgr2 remains unchanged.
         //
         pgr = new PlanetographicCoordinates( Moon, 1.0, 2.0, -1000.0,
                                                                   re/2, f/2 );



         ok  = JNITestutils.chcksd ( "longitude",
                                     pgr2.getLongitude(),
                                     "~",
                                     longitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "latitude",
                                     pgr2.getLatitude(),
                                     "~",
                                     latitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "altitude",
                                     pgr2.getAltitude(),
                                     "~",
                                     altitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "RE",
                                     pgr2.getEquatorialRadius(),
                                     "~",
                                     re,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "F",
                                     pgr2.getFlatteningCoefficient(),
                                     "~",
                                     f,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksi ( "Body",
                                     pgr2.getBody().getIDCode(),
                                     "=",
                                     399,
                                     0                         );


         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "Construct planetographic coordinates from " +
                              "a vector."                              );


         //
         // Generate the vector we'll use.
         //
         re        = 6378.14;
         rp        = 6356.75;

         f         = ( re - rp ) / re;

         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         altitude  = 10.0;

         pgr = new PlanetographicCoordinates( Moon, longitude, latitude,
                                                             altitude, re, f );

         pos = pgr.toRectangular();


         //
         // Convert the vector back to planetographic coordinates.
         //
         pgr2 = new PlanetographicCoordinates( Moon, pos, re, f );


         ok  = JNITestutils.chcksd ( "longitude",
                                     pgr2.getLongitude(),
                                     "~/",
                                     longitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "latitude",
                                     pgr2.getLatitude(),
                                     "~/",
                                     latitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "altitude",
                                     pgr2.getAltitude(),
                                     "~/",
                                     altitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "RE",
                                     pgr2.getEquatorialRadius(),
                                     "~/",
                                     re,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "F",
                                     pgr2.getFlatteningCoefficient(),
                                     "~/",
                                     f,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksi ( "Body",
                                     pgr2.getBody().getIDCode(),
                                     "=",
                                     301,
                                     0                         );



         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "getPgrRecJacobian: verify Jacobian matrix " +
                              "for certain trivial cases."                   );


         //
         // Generate the coordinates we'll use for the planetographic-to-
         // rectangular transformation.
         //
         re        = 2.0;
         rp        = 2.0;

         f         = ( re - rp ) / re;

         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         altitude  =  0.0;

         pgr    = new PlanetographicCoordinates( Earth, longitude, latitude,
                                                             altitude, re, f );

         jac1   = pgr.getPgrRecJacobian();


         //
         // At pos, x == 2*cos(lat)*cos(lon); dx/dlon
         // == -2*cos(lat)*sin(lon) == -2 * 0.5 * 0.5
         //

         ok  = JNITestutils.chcksd ( "dx/dlon",
                                     jac1.getElt(0,0),
                                     "~",
                                     -0.5,
                                     TIGHT_TOL );
         //
         // At pos, y == 2*cos(lat)*sin(lon); dy/dlon
         // == 2*cos(lat)*cos(lon) == 2 * 0.5 * sqrt(3)/2
         //

         ok  = JNITestutils.chcksd ( "dy/dlon",
                                     jac1.getElt(1,0),
                                     "~",
                                     SQ3/2,
                                     TIGHT_TOL );

         //
         // At pos, z == 2*sin(lat); dz/dlon == 0
         //

         ok  = JNITestutils.chcksd ( "dz/dlon",
                                     jac1.getElt(2,0),
                                     "~",
                                     0.0,
                                     TIGHT_TOL );

         //
         // At pos, x == 2*cos(lat)*cos(lon); dx/dlat
         // == -2*sin(lat)*cos(lon) == -2*(sqrt(3)/2)*(sqrt(3)/2)
         //

         ok  = JNITestutils.chcksd ( "dx/dlat",
                                     jac1.getElt(0,1),
                                     "~",
                                     -1.5,
                                     TIGHT_TOL );

         //
         // At pos, y == 2*cos(lat)*sin(lon); dy/dlat
         // == -2*sin(lat)*sin(lon) == -sqrt(3)/2
         //
         ok  = JNITestutils.chcksd ( "dy/dlat",
                                     jac1.getElt(1,1),
                                     "~",
                                     -SQ3/2,
                                     TIGHT_TOL );

         //
         // At pos, z == 2*sin(lat); dz/dlat == 2*cos(lat) == 1
         //
         ok  = JNITestutils.chcksd ( "dz/dlat",
                                     jac1.getElt(2,1),
                                     "~",
                                     1.0,
                                     TIGHT_TOL );



         //
         // At pos, x == (2+alt)*cos(lat)*cos(lon); dx/dalt
         // == cos(lat)*cos(lon) == 0.5*(sqrt(3)/2)
         //

         ok  = JNITestutils.chcksd ( "dx/dalt",
                                     jac1.getElt(0,2),
                                     "~",
                                     SQ3/4,
                                     TIGHT_TOL );

         //
         // At pos, y == (2+alt)*cos(lat)*sin(lon); dy/dalt
         // == cos(lat)*sin(lon) == 0.5*0.5
         //

         ok  = JNITestutils.chcksd ( "dy/dalt",
                                     jac1.getElt(1,2),
                                     "~",
                                     0.25,
                                     TIGHT_TOL );

         //
         // At pos, z == (2+alt)*sin(lat); dz/dalt
         // == sin(lat) == sqrt(3)/2
         //

         ok  = JNITestutils.chcksd ( "dz/dalt",
                                     jac1.getElt(2,2),
                                     "~",
                                     SQ3/2,
                                     TIGHT_TOL );



         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "getPgrRecJacobian: verify Jacobian matrix " +
                              "is inverse of that obtained from " +
                              "getRecPgrJacobian."                          );


         //
         // Generate the coordinates we'll use for the planetographic-to-
         // rectangular transformation.
         //
         re        = 6378.14;
         rp        = 6356.75;

         f         = ( re - rp ) / re;

         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         altitude  = 10.0;

         pgr    = new PlanetographicCoordinates( Earth, longitude, latitude,
                                                             altitude, re, f );

         jac1   = pgr.getPgrRecJacobian();

         pos    = pgr.toRectangular();

         jac2   = PlanetographicCoordinates.getRecPgrJacobian( Earth, pos,
                                                                       re, f );

         invmat = jac2.invert();

         dist   = jac1.dist( invmat );


         ok  = JNITestutils.chcksd ( "dist",
                                     dist,
                                     "~",
                                     0.0,
                                     TIGHT_TOL );

         //System.out.println( invmat );
      }

      catch ( SpiceException ex )
      {
         //
         //  Getting here means we've encountered an unexpected
         //  SPICE exception.  This is analogous to encountering
         //  an unexpected SPICE error in CSPICE.
         //

         ex.printStackTrace();

         ok = JNITestutils.chckth ( false, "", ex );
      }

      //
      // Retrieve the current test status.
      //
      ok = JNITestutils.tsuccess();

      return ( ok );
   }

}

