
package spice.tspice;


import java.io.*;
import java.util.*;
import spice.basic.*;
import spice.testutils.JNITestutils;
import spice.testutils.Testutils;
import static spice.basic.AngularUnits.*;

/**
Class TestLatitudinalCoordinates provides methods that
implement test families for the class LatitudinalCoordinates.

<p>Version 1.0.0 23-NOV-2009 (NJB)
*/
public class TestLatitudinalCoordinates extends Object
{

   //
   // Class constants
   //


   //
   // Class variables
   //


   //
   // Methods
   //

   /**
   Test LatitudinalCoordinates and associated classes.
   */
   public static boolean f_LatitudinalCoordinates()

      throws SpiceException
   {
      //
      // Constants
      //
      final double                      TIGHT_TOL = 1.e-12;
      final double                      MED_TOL   = 1.e-9;

      final double                      SQ3       = Math.sqrt(3.0);
      //
      // Local variables
      //
      Body                              Earth;

      LatitudinalCoordinates            lat1;
      LatitudinalCoordinates            lat2;

      Matrix33                          jac1;
      Matrix33                          jac2;
      Matrix33                          invmat;

      Vector3                           pos;
      Vector3                           xPos;

      boolean                           ok;

      double                            dist;
      double                            latitude;
      double                            longitude;
      double[]                          radii;
      double                            radius;
      double                            xLatitude;
      double                            xLongitude;
      double                            xRadius;


      //
      //  We enclose all tests in a try/catch block in order to
      //  facilitate handling unexpected exceptions.  Unexpected
      //  exceptions are trapped by the catch block at the end of
      //  the routine; expected exceptions are handled locally by
      //  catch blocks associated with error handling test cases.
      //
      //  Therefore, JNISpice calls that are expected to succeed don't
      //  have any subsequent "chckxc" type calls following them, nor
      //  are they wrapped in in try/catch blocks.
      //
      //  Expected exceptions that are *not* thrown are tested
      //  via a call to {@link spice.testutils.Testutils#dogDidNotBark}.
      //

      try
      {

         JNITestutils.topen ( "f_LatitudinalCoordinates" );




         // ***********************************************************
         //
         //    Error cases
         //
         // ***********************************************************


         //
         // We don't need to test every exception that can occur, but
         // we must:
         //
         //    - Test every exception generated in the Java API layer.
         //
         //    - Test at least one exception generated by CSPICE for
         //      every CSPICE class wrapper.
         //



         //
         // --------Case-----------------------------------------------
         //
         JNITestutils.tcase (  "Error: negative radius in lat/lon/radius-" +
                               "based constructor call. "   );

         try
         {
            radius    = -1.0;
            longitude = 0.5;
            latitude  = 0.25;

            lat1 = new LatitudinalCoordinates( radius, longitude, latitude );

            //
            // If an exception is *not* thrown, we'll hit this call.
            //

            Testutils.dogDidNotBark (  "SPICE(VALUEOUTOFRANGE)" );

         }
         catch ( SpiceException ex )
         {
            ok = JNITestutils.chckth ( true,   "SPICE(VALUEOUTOFRANGE)", ex );
         }

         //
         // --------Case-----------------------------------------------
         //
         JNITestutils.tcase (  "Error: singular input case in rectangular to " +
                               "latitudinal vector-based Jacobian call. "   );

         try
         {

            pos  = new Vector3( 0.0, 0.0, 0.0 );

            jac1 = LatitudinalCoordinates.getRecLatJacobian( pos );

            //
            // If an exception is *not* thrown, we'll hit this call.
            //

            Testutils.dogDidNotBark (  "SPICE(POINTONZAXIS)" );

         }
         catch ( SpiceException ex )
         {
            ok = JNITestutils.chckth ( true,   "SPICE(POINTONZAXIS)", ex );
         }







         // ***********************************************************
         //
         //    Normal cases
         //
         // ***********************************************************


         //
         // Constructor tests:
         //


         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "Construct latitudinal coordinates for a " +
                              "surface point on the unit sphere. Use " +
                              "scalar latitudinal coordinate constructor."   );

         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         radius    =  1.0;

         lat1 = new LatitudinalCoordinates( radius, longitude, latitude );

         pos  = lat1.toRectangular();

         ok  = JNITestutils.chcksd ( "X coordinate",
                                     pos.toArray()[0],
                                     "~",
                                     SQ3/4,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "Y coordinate",
                                     pos.toArray()[1],
                                     "~",
                                     0.25,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "Z coordinate",
                                     pos.toArray()[2],
                                     "~",
                                     SQ3/2,
                                     TIGHT_TOL          );



         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "Construct latitudinal coordinates for a " +
                              "surface point on the Earth.  Use scalar " +
                              "latitudinal coordinate constructor."          );


         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         radius    = 6370.0;

         lat1 = new LatitudinalCoordinates( radius, longitude, latitude );



         ok  = JNITestutils.chcksd ( "longitude",
                                     lat1.getLongitude(),
                                     "~",
                                     longitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "latitude",
                                     lat1.getLatitude(),
                                     "~",
                                     latitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "radius",
                                     lat1.getRadius(),
                                     "~",
                                     radius,
                                     TIGHT_TOL          );



         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "Test copy constructor." );


         lat2 = new LatitudinalCoordinates( lat1 );

         //
         // Change lat1; make sure lat2 remains unchanged.
         //
         lat1 = new LatitudinalCoordinates( 1000.0, 1.0, 2.0 );



         ok  = JNITestutils.chcksd ( "longitude",
                                     lat2.getLongitude(),
                                     "~",
                                     longitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "latitude",
                                     lat2.getLatitude(),
                                     "~",
                                     latitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "radius",
                                     lat2.getRadius(),
                                     "~",
                                     radius,
                                     TIGHT_TOL          );


         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "Construct latitudinal coordinates from " +
                              "a vector."                              );


         //
         // Generate the vector we'll use.
         //
         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         radius    = 6370.0;

         lat1 = new LatitudinalCoordinates( radius, longitude, latitude );

         pos = lat1.toRectangular();


         //
         // Convert the vector back to latitudinal coordinates.
         //
         lat2 = new LatitudinalCoordinates( pos );


         ok  = JNITestutils.chcksd ( "longitude",
                                     lat2.getLongitude(),
                                     "~",
                                     longitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "latitude",
                                     lat2.getLatitude(),
                                     "~",
                                     latitude,
                                     TIGHT_TOL          );

         ok  = JNITestutils.chcksd ( "radius",
                                     lat2.getRadius(),
                                     "~",
                                     radius,
                                     TIGHT_TOL          );



         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "getLatRecJacobian: verify Jacobian matrix " +
                              "for certain trivial cases."                   );


         //
         // Generate the coordinates we'll use for the latitudinal-to-
         // rectangular transformation.
         //

         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         radius    =  2.0;

         lat1   = new LatitudinalCoordinates( radius, longitude, latitude );

         jac1   = lat1.getLatRecJacobian();


         //
         // At pos, x == (rad)*cos(lat)*cos(lon); dx/drad
         // == cos(lat)*cos(lon) == 0.5*(sqrt(3)/2)
         //

         ok  = JNITestutils.chcksd ( "dx/drad",
                                     jac1.getElt(0,0),
                                     "~",
                                     SQ3/4,
                                     TIGHT_TOL );

         //
         // At pos, y == (rad)*cos(lat)*sin(lon); dy/drad
         // == cos(lat)*sin(lon) == 0.5*0.5
         //

         ok  = JNITestutils.chcksd ( "dy/drad",
                                     jac1.getElt(1,0),
                                     "~",
                                     0.25,
                                     TIGHT_TOL );

         //
         // At pos, z == (rad)*sin(lat); dz/drad
         // == sin(lat) == sqrt(3)/2
         //

         ok  = JNITestutils.chcksd ( "dz/drad",
                                     jac1.getElt(2,0),
                                     "~",
                                     SQ3/2,
                                     TIGHT_TOL );


         //
         // At pos, x == 2*cos(lat)*cos(lon); dx/dlon
         // == -2*cos(lat)*sin(lon) == -2 * 0.5 * 0.5
         //

         ok  = JNITestutils.chcksd ( "dx/dlon",
                                     jac1.getElt(0,1),
                                     "~",
                                     -0.5,
                                     TIGHT_TOL );
         //
         // At pos, y == 2*cos(lat)*sin(lon); dy/dlon
         // == 2*cos(lat)*cos(lon) == 2 * 0.5 * sqrt(3)/2
         //

         ok  = JNITestutils.chcksd ( "dy/dlon",
                                     jac1.getElt(1,1),
                                     "~",
                                     SQ3/2,
                                     TIGHT_TOL );

         //
         // At pos, z == 2*sin(lat); dz/dlon == 0
         //

         ok  = JNITestutils.chcksd ( "dz/dlon",
                                     jac1.getElt(2,1),
                                     "~",
                                     0.0,
                                     TIGHT_TOL );

         //
         // At pos, x == 2*cos(lat)*cos(lon); dx/dlat
         // == -2*sin(lat)*cos(lon) == -2*(sqrt(3)/2)*(sqrt(3)/2)
         //

         ok  = JNITestutils.chcksd ( "dx/dlat",
                                     jac1.getElt(0,2),
                                     "~",
                                     -1.5,
                                     TIGHT_TOL );

         //
         // At pos, y == 2*cos(lat)*sin(lon); dy/dlat
         // == -2*sin(lat)*sin(lon) == -sqrt(3)/2
         //
         ok  = JNITestutils.chcksd ( "dy/dlat",
                                     jac1.getElt(1,2),
                                     "~",
                                     -SQ3/2,
                                     TIGHT_TOL );

         //
         // At pos, z == 2*sin(lat); dz/dlat == 2*cos(lat) == 1
         //
         ok  = JNITestutils.chcksd ( "dz/dlat",
                                     jac1.getElt(2,2),
                                     "~",
                                     1.0,
                                     TIGHT_TOL );





         //
         // --------Case-----------------------------------------------
         //

         JNITestutils.tcase ( "getLatRecJacobian: verify Jacobian matrix " +
                              "is inverse of that obtained from " +
                              "getRecLatJacobian."                          );


         //
         // Generate the coordinates we'll use for the latitudinal-to-
         // rectangular transformation.

         longitude = 30.0 * RPD;
         latitude  = 60.0 * RPD;
         radius    = 6370.0;

         lat1   = new LatitudinalCoordinates( radius, longitude, latitude );

         jac1   = lat1.getLatRecJacobian();

         pos    = lat1.toRectangular();

         jac2   = LatitudinalCoordinates.getRecLatJacobian( pos );

         invmat = jac2.invert();

         dist   = jac1.dist( invmat );


         ok  = JNITestutils.chcksd ( "dist",
                                     dist,
                                     "~",
                                     0.0,
                                     MED_TOL );

         //System.out.println( invmat );
      }

      catch ( SpiceException ex )
      {
         //
         //  Getting here means we've encountered an unexpected
         //  SPICE exception.  This is analogous to encountering
         //  an unexpected SPICE error in CSPICE.
         //

         ex.printStackTrace();

         ok = JNITestutils.chckth ( false, "", ex );
      }

      //
      // Retrieve the current test status.
      //
      ok = JNITestutils.tsuccess();

      return ( ok );
   }

}

