package gov.nasa.jpl.aerie.contrib.streamline.modeling.discrete.monads;

import gov.nasa.jpl.aerie.contrib.streamline.modeling.discrete.Discrete;
import gov.nasa.jpl.aerie.contrib.streamline.utils.*;
import org.apache.commons.lang3.function.TriFunction;

import java.util.function.BiFunction;
import java.util.function.Function;

import static gov.nasa.jpl.aerie.contrib.streamline.modeling.discrete.Discrete.discrete;
import static gov.nasa.jpl.aerie.contrib.streamline.utils.FunctionalUtils.curry;

/**
 * {@link Discrete} monad
 */
public final class DiscreteMonad {
  private DiscreteMonad() {}

  public static <A> Discrete<A> pure(A a) {
    return discrete(a);
  }

  public static <A, B> Discrete<B> apply(Discrete<A> a, Discrete<Function<A, B>> f) {
    return discrete(f.extract().apply(a.extract()));
  }

  public static <A> Discrete<A> join(Discrete<Discrete<A>> a) {
    return a.extract();
  }

  // GENERATED CODE START
  // Supplemental methods generated by generate_monad_methods.py on 2023-12-06.
  
  public static <A, B> Function<Discrete<A>, Discrete<B>> apply(Discrete<Function<A, B>> f) {
    return a -> apply(a, f);
  }
  
  public static <A, B> Discrete<B> map(Discrete<A> a, Function<A, B> f) {
    return apply(a, pure(f));
  }
  
  public static <A, B> Function<Discrete<A>, Discrete<B>> map(Function<A, B> f) {
    return apply(pure(f));
  }
  
  public static <A, B> Discrete<B> bind(Discrete<A> a, Function<A, Discrete<B>> f) {
    return join(map(a, f));
  }
  
  public static <A, B> Function<Discrete<A>, Discrete<B>> bind(Function<A, Discrete<B>> f) {
    return a -> bind(a, f);
  }
  
  public static <A, B, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, BiFunction<A, B, Result> function) {
    return map(a, b, curry(function));
  }
  
  public static <A, B, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Function<A, Function<B, Result>> function) {
    return apply(b, map(a, function));
  }
  
  public static <A, B, Result> BiFunction<Discrete<A>, Discrete<B>, Discrete<Result>> map(BiFunction<A, B, Result> function) {
    return (a, b) -> map(a, b, function);
  }
  
  public static <A, B, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, BiFunction<A, B, Discrete<Result>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Function<A, Function<B, Discrete<Result>>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> BiFunction<Discrete<A>, Discrete<B>, Discrete<Result>> bind(BiFunction<A, B, Discrete<Result>> function) {
    return (a, b) -> bind(a, b, function);
  }
  
  public static <A, B, C, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, TriFunction<A, B, C, Result> function) {
    return map(a, b, c, curry(function));
  }
  
  public static <A, B, C, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Function<A, Function<B, Function<C, Result>>> function) {
    return apply(c, map(a, b, function));
  }
  
  public static <A, B, C, Result> TriFunction<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<Result>> map(TriFunction<A, B, C, Result> function) {
    return (a, b, c) -> map(a, b, c, function);
  }
  
  public static <A, B, C, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, TriFunction<A, B, C, Discrete<Result>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Function<A, Function<B, Function<C, Discrete<Result>>>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> TriFunction<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<Result>> bind(TriFunction<A, B, C, Discrete<Result>> function) {
    return (a, b, c) -> bind(a, b, c, function);
  }
  
  public static <A, B, C, D, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Function4<A, B, C, D, Result> function) {
    return map(a, b, c, d, curry(function));
  }
  
  public static <A, B, C, D, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Function<A, Function<B, Function<C, Function<D, Result>>>> function) {
    return apply(d, map(a, b, c, function));
  }
  
  public static <A, B, C, D, Result> Function4<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<Result>> map(Function4<A, B, C, D, Result> function) {
    return (a, b, c, d) -> map(a, b, c, d, function);
  }
  
  public static <A, B, C, D, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Function4<A, B, C, D, Discrete<Result>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Function<A, Function<B, Function<C, Function<D, Discrete<Result>>>>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> Function4<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<Result>> bind(Function4<A, B, C, D, Discrete<Result>> function) {
    return (a, b, c, d) -> bind(a, b, c, d, function);
  }
  
  public static <A, B, C, D, E, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Function5<A, B, C, D, E, Result> function) {
    return map(a, b, c, d, e, curry(function));
  }
  
  public static <A, B, C, D, E, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, Result>>>>> function) {
    return apply(e, map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<Result>> map(Function5<A, B, C, D, E, Result> function) {
    return (a, b, c, d, e) -> map(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Function5<A, B, C, D, E, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, Discrete<Result>>>>>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<Result>> bind(Function5<A, B, C, D, E, Discrete<Result>> function) {
    return (a, b, c, d, e) -> bind(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, F, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Function6<A, B, C, D, E, F, Result> function) {
    return map(a, b, c, d, e, f, curry(function));
  }
  
  public static <A, B, C, D, E, F, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Result>>>>>> function) {
    return apply(f, map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<Result>> map(Function6<A, B, C, D, E, F, Result> function) {
    return (a, b, c, d, e, f) -> map(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Function6<A, B, C, D, E, F, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Discrete<Result>>>>>>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<Result>> bind(Function6<A, B, C, D, E, F, Discrete<Result>> function) {
    return (a, b, c, d, e, f) -> bind(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Function7<A, B, C, D, E, F, G, Result> function) {
    return map(a, b, c, d, e, f, g, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Result>>>>>>> function) {
    return apply(g, map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<Result>> map(Function7<A, B, C, D, E, F, G, Result> function) {
    return (a, b, c, d, e, f, g) -> map(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Function7<A, B, C, D, E, F, G, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Discrete<Result>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<Result>> bind(Function7<A, B, C, D, E, F, G, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g) -> bind(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Function8<A, B, C, D, E, F, G, H, Result> function) {
    return map(a, b, c, d, e, f, g, h, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Result>>>>>>>> function) {
    return apply(h, map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<Result>> map(Function8<A, B, C, D, E, F, G, H, Result> function) {
    return (a, b, c, d, e, f, g, h) -> map(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Function8<A, B, C, D, E, F, G, H, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Discrete<Result>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<Result>> bind(Function8<A, B, C, D, E, F, G, H, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h) -> bind(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Result>>>>>>>>> function) {
    return apply(i, map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<Result>> map(Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return (a, b, c, d, e, f, g, h, i) -> map(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Function9<A, B, C, D, E, F, G, H, I, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Discrete<Result>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<Result>> bind(Function9<A, B, C, D, E, F, G, H, I, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i) -> bind(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Result>>>>>>>>>> function) {
    return apply(j, map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<Result>> map(Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> map(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Function10<A, B, C, D, E, F, G, H, I, J, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Discrete<Result>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<Result>> bind(Function10<A, B, C, D, E, F, G, H, I, J, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> bind(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Result>>>>>>>>>>> function) {
    return apply(k, map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<Result>> map(Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> map(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Discrete<Result>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<Result>> bind(Function11<A, B, C, D, E, F, G, H, I, J, K, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> bind(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Result>>>>>>>>>>>> function) {
    return apply(l, map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<Result>> map(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> map(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Discrete<Result>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<Result>> bind(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Result>>>>>>>>>>>>> function) {
    return apply(m, map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<Result>> map(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Discrete<Result>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<Result>> bind(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Result>>>>>>>>>>>>>> function) {
    return apply(n, map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<Result>> map(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Discrete<Result>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<Result>> bind(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Result>>>>>>>>>>>>>>> function) {
    return apply(o, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<Result>> map(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Discrete<Result>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<Result>> bind(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Result>>>>>>>>>>>>>>>> function) {
    return apply(p, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Result>> map(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Discrete<Result>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Result>> bind(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Result>>>>>>>>>>>>>>>>> function) {
    return apply(q, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Q>, Discrete<Result>> map(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Discrete<Result>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Q>, Discrete<Result>> bind(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Result>>>>>>>>>>>>>>>>>> function) {
    return apply(r, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Q>, Discrete<R>, Discrete<Result>> map(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Discrete<Result>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Q>, Discrete<R>, Discrete<Result>> bind(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Discrete<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Discrete<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Result>>>>>>>>>>>>>>>>>>> function) {
    return apply(s, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Q>, Discrete<R>, Discrete<S>, Discrete<Result>> map(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Discrete<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Discrete<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Discrete<Result>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Q>, Discrete<R>, Discrete<S>, Discrete<Result>> bind(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Discrete<S> s, Discrete<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Discrete<Result> map(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Discrete<S> s, Discrete<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Result>>>>>>>>>>>>>>>>>>>> function) {
    return apply(t, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Q>, Discrete<R>, Discrete<S>, Discrete<T>, Discrete<Result>> map(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Discrete<S> s, Discrete<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Discrete<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Discrete<Result> bind(Discrete<A> a, Discrete<B> b, Discrete<C> c, Discrete<D> d, Discrete<E> e, Discrete<F> f, Discrete<G> g, Discrete<H> h, Discrete<I> i, Discrete<J> j, Discrete<K> k, Discrete<L> l, Discrete<M> m, Discrete<N> n, Discrete<O> o, Discrete<P> p, Discrete<Q> q, Discrete<R> r, Discrete<S> s, Discrete<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Discrete<Result>>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>, Discrete<K>, Discrete<L>, Discrete<M>, Discrete<N>, Discrete<O>, Discrete<P>, Discrete<Q>, Discrete<R>, Discrete<S>, Discrete<T>, Discrete<Result>> bind(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Discrete<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  // GENERATED CODE END
}
