package gov.nasa.jpl.aerie.contrib.streamline.modeling.discrete.monads;

import gov.nasa.jpl.aerie.contrib.streamline.modeling.discrete.Discrete;
import gov.nasa.jpl.aerie.contrib.streamline.core.Resource;
import gov.nasa.jpl.aerie.contrib.streamline.core.monads.ResourceMonad;
import gov.nasa.jpl.aerie.contrib.streamline.utils.*;
import org.apache.commons.lang3.function.TriFunction;

import java.util.function.BiFunction;
import java.util.function.Function;

import static gov.nasa.jpl.aerie.contrib.streamline.utils.FunctionalUtils.curry;

public final class DiscreteResourceMonad {
  private DiscreteResourceMonad() {}

  public static <A> Resource<Discrete<A>> pure(A a) {
    return ResourceMonad.pure(DiscreteMonad.pure(a));
  }

  public static <A, B> Resource<Discrete<B>> apply(Resource<Discrete<A>> a, Resource<Discrete<Function<A, B>>> f) {
    return ResourceMonad.apply(a, ResourceMonad.map(f, DiscreteMonad::apply));
  }

  private static <A> Resource<Discrete<A>> distribute(Discrete<Resource<A>> a) {
    return ResourceMonad.map(a.extract(), DiscreteMonad::pure);
  }

  public static <A> Resource<Discrete<A>> join(Resource<Discrete<Resource<Discrete<A>>>> a) {
    return ResourceMonad.map(ResourceMonad.join(ResourceMonad.map(a, DiscreteResourceMonad::distribute)), DiscreteMonad::join);
  }

  // GENERATED CODE START
  // Supplemental methods generated by generate_monad_methods.py on 2023-11-28.
  
  public static <A, B> Function<Resource<Discrete<A>>, Resource<Discrete<B>>> apply(Resource<Discrete<Function<A, B>>> f) {
    return a -> apply(a, f);
  }
  
  public static <A, B> Resource<Discrete<B>> map(Resource<Discrete<A>> a, Function<A, B> f) {
    return apply(a, pure(f));
  }
  
  public static <A, B> Function<Resource<Discrete<A>>, Resource<Discrete<B>>> map(Function<A, B> f) {
    return apply(pure(f));
  }
  
  public static <A, B> Resource<Discrete<B>> bind(Resource<Discrete<A>> a, Function<A, Resource<Discrete<B>>> f) {
    return join(map(a, f));
  }
  
  public static <A, B> Function<Resource<Discrete<A>>, Resource<Discrete<B>>> bind(Function<A, Resource<Discrete<B>>> f) {
    return a -> bind(a, f);
  }
  
  public static <A, B, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, BiFunction<A, B, Result> function) {
    return map(a, b, curry(function));
  }
  
  public static <A, B, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Function<A, Function<B, Result>> function) {
    return apply(b, map(a, function));
  }
  
  public static <A, B, Result> BiFunction<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<Result>>> map(BiFunction<A, B, Result> function) {
    return (a, b) -> map(a, b, function);
  }
  
  public static <A, B, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, BiFunction<A, B, Resource<Discrete<Result>>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Function<A, Function<B, Resource<Discrete<Result>>>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> BiFunction<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<Result>>> bind(BiFunction<A, B, Resource<Discrete<Result>>> function) {
    return (a, b) -> bind(a, b, function);
  }
  
  public static <A, B, C, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, TriFunction<A, B, C, Result> function) {
    return map(a, b, c, curry(function));
  }
  
  public static <A, B, C, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Function<A, Function<B, Function<C, Result>>> function) {
    return apply(c, map(a, b, function));
  }
  
  public static <A, B, C, Result> TriFunction<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<Result>>> map(TriFunction<A, B, C, Result> function) {
    return (a, b, c) -> map(a, b, c, function);
  }
  
  public static <A, B, C, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, TriFunction<A, B, C, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Function<A, Function<B, Function<C, Resource<Discrete<Result>>>>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> TriFunction<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<Result>>> bind(TriFunction<A, B, C, Resource<Discrete<Result>>> function) {
    return (a, b, c) -> bind(a, b, c, function);
  }
  
  public static <A, B, C, D, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Function4<A, B, C, D, Result> function) {
    return map(a, b, c, d, curry(function));
  }
  
  public static <A, B, C, D, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Function<A, Function<B, Function<C, Function<D, Result>>>> function) {
    return apply(d, map(a, b, c, function));
  }
  
  public static <A, B, C, D, Result> Function4<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<Result>>> map(Function4<A, B, C, D, Result> function) {
    return (a, b, c, d) -> map(a, b, c, d, function);
  }
  
  public static <A, B, C, D, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Function4<A, B, C, D, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Function<A, Function<B, Function<C, Function<D, Resource<Discrete<Result>>>>>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> Function4<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<Result>>> bind(Function4<A, B, C, D, Resource<Discrete<Result>>> function) {
    return (a, b, c, d) -> bind(a, b, c, d, function);
  }
  
  public static <A, B, C, D, E, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Function5<A, B, C, D, E, Result> function) {
    return map(a, b, c, d, e, curry(function));
  }
  
  public static <A, B, C, D, E, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Function<A, Function<B, Function<C, Function<D, Function<E, Result>>>>> function) {
    return apply(e, map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<Result>>> map(Function5<A, B, C, D, E, Result> function) {
    return (a, b, c, d, e) -> map(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Function5<A, B, C, D, E, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Function<A, Function<B, Function<C, Function<D, Function<E, Resource<Discrete<Result>>>>>>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<Result>>> bind(Function5<A, B, C, D, E, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e) -> bind(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, F, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Function6<A, B, C, D, E, F, Result> function) {
    return map(a, b, c, d, e, f, curry(function));
  }
  
  public static <A, B, C, D, E, F, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Result>>>>>> function) {
    return apply(f, map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<Result>>> map(Function6<A, B, C, D, E, F, Result> function) {
    return (a, b, c, d, e, f) -> map(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Function6<A, B, C, D, E, F, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Resource<Discrete<Result>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<Result>>> bind(Function6<A, B, C, D, E, F, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f) -> bind(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Function7<A, B, C, D, E, F, G, Result> function) {
    return map(a, b, c, d, e, f, g, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Result>>>>>>> function) {
    return apply(g, map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<Result>>> map(Function7<A, B, C, D, E, F, G, Result> function) {
    return (a, b, c, d, e, f, g) -> map(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Function7<A, B, C, D, E, F, G, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Resource<Discrete<Result>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<Result>>> bind(Function7<A, B, C, D, E, F, G, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g) -> bind(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Function8<A, B, C, D, E, F, G, H, Result> function) {
    return map(a, b, c, d, e, f, g, h, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Result>>>>>>>> function) {
    return apply(h, map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<Result>>> map(Function8<A, B, C, D, E, F, G, H, Result> function) {
    return (a, b, c, d, e, f, g, h) -> map(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Function8<A, B, C, D, E, F, G, H, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Resource<Discrete<Result>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<Result>>> bind(Function8<A, B, C, D, E, F, G, H, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h) -> bind(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Result>>>>>>>>> function) {
    return apply(i, map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<Result>>> map(Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return (a, b, c, d, e, f, g, h, i) -> map(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Function9<A, B, C, D, E, F, G, H, I, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Resource<Discrete<Result>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<Result>>> bind(Function9<A, B, C, D, E, F, G, H, I, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i) -> bind(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Result>>>>>>>>>> function) {
    return apply(j, map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<Result>>> map(Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> map(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Function10<A, B, C, D, E, F, G, H, I, J, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Resource<Discrete<Result>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<Result>>> bind(Function10<A, B, C, D, E, F, G, H, I, J, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> bind(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Result>>>>>>>>>>> function) {
    return apply(k, map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<Result>>> map(Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> map(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Resource<Discrete<Result>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<Result>>> bind(Function11<A, B, C, D, E, F, G, H, I, J, K, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> bind(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Result>>>>>>>>>>>> function) {
    return apply(l, map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<Result>>> map(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> map(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Resource<Discrete<Result>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<Result>>> bind(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Result>>>>>>>>>>>>> function) {
    return apply(m, map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<Result>>> map(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Resource<Discrete<Result>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<Result>>> bind(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Result>>>>>>>>>>>>>> function) {
    return apply(n, map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<Result>>> map(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Resource<Discrete<Result>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<Result>>> bind(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Result>>>>>>>>>>>>>>> function) {
    return apply(o, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<Result>>> map(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Resource<Discrete<Result>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<Result>>> bind(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Result>>>>>>>>>>>>>>>> function) {
    return apply(p, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Result>>> map(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Resource<Discrete<Result>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Result>>> bind(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Result>>>>>>>>>>>>>>>>> function) {
    return apply(q, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Q>>, Resource<Discrete<Result>>> map(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Resource<Discrete<Result>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Q>>, Resource<Discrete<Result>>> bind(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Result>>>>>>>>>>>>>>>>>> function) {
    return apply(r, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Q>>, Resource<Discrete<R>>, Resource<Discrete<Result>>> map(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Resource<Discrete<Result>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Q>>, Resource<Discrete<R>>, Resource<Discrete<Result>>> bind(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Resource<Discrete<S>> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Resource<Discrete<S>> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Result>>>>>>>>>>>>>>>>>>> function) {
    return apply(s, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Q>>, Resource<Discrete<R>>, Resource<Discrete<S>>, Resource<Discrete<Result>>> map(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Resource<Discrete<S>> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Resource<Discrete<S>> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Resource<Discrete<Result>>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Q>>, Resource<Discrete<R>>, Resource<Discrete<S>>, Resource<Discrete<Result>>> bind(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Resource<Discrete<S>> s, Resource<Discrete<T>> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Resource<Discrete<Result>> map(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Resource<Discrete<S>> s, Resource<Discrete<T>> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Result>>>>>>>>>>>>>>>>>>>> function) {
    return apply(t, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Q>>, Resource<Discrete<R>>, Resource<Discrete<S>>, Resource<Discrete<T>>, Resource<Discrete<Result>>> map(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Resource<Discrete<S>> s, Resource<Discrete<T>> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Resource<Discrete<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Resource<Discrete<Result>> bind(Resource<Discrete<A>> a, Resource<Discrete<B>> b, Resource<Discrete<C>> c, Resource<Discrete<D>> d, Resource<Discrete<E>> e, Resource<Discrete<F>> f, Resource<Discrete<G>> g, Resource<Discrete<H>> h, Resource<Discrete<I>> i, Resource<Discrete<J>> j, Resource<Discrete<K>> k, Resource<Discrete<L>> l, Resource<Discrete<M>> m, Resource<Discrete<N>> n, Resource<Discrete<O>> o, Resource<Discrete<P>> p, Resource<Discrete<Q>> q, Resource<Discrete<R>> r, Resource<Discrete<S>> s, Resource<Discrete<T>> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Resource<Discrete<Result>>>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<Resource<Discrete<A>>, Resource<Discrete<B>>, Resource<Discrete<C>>, Resource<Discrete<D>>, Resource<Discrete<E>>, Resource<Discrete<F>>, Resource<Discrete<G>>, Resource<Discrete<H>>, Resource<Discrete<I>>, Resource<Discrete<J>>, Resource<Discrete<K>>, Resource<Discrete<L>>, Resource<Discrete<M>>, Resource<Discrete<N>>, Resource<Discrete<O>>, Resource<Discrete<P>>, Resource<Discrete<Q>>, Resource<Discrete<R>>, Resource<Discrete<S>>, Resource<Discrete<T>>, Resource<Discrete<Result>>> bind(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Resource<Discrete<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  // GENERATED CODE END
}
