package gov.nasa.jpl.aerie.contrib.streamline.core.monads;

import gov.nasa.jpl.aerie.contrib.streamline.core.Dynamics;
import gov.nasa.jpl.aerie.contrib.streamline.core.DynamicsEffect;
import gov.nasa.jpl.aerie.contrib.streamline.core.ErrorCatching;
import gov.nasa.jpl.aerie.contrib.streamline.core.Expiring;
import gov.nasa.jpl.aerie.contrib.streamline.utils.*;
import org.apache.commons.lang3.function.TriFunction;

import java.util.function.BiFunction;
import java.util.function.Function;

import static gov.nasa.jpl.aerie.contrib.streamline.core.Expiring.expiring;
import static gov.nasa.jpl.aerie.contrib.streamline.utils.FunctionalUtils.curry;

public final class DynamicsMonad {
  private DynamicsMonad() {}

  public static <A> ErrorCatching<Expiring<A>> pure(A a) {
    return ErrorCatchingMonad.pure(ExpiringMonad.pure(a));
  }

  public static <A, B> ErrorCatching<Expiring<B>> apply(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<Function<A, B>>> f) {
    return ErrorCatchingMonad.apply(a, ErrorCatchingMonad.map(f, ExpiringMonad::apply));
  }

  private static <A> ErrorCatching<Expiring<A>> distribute(Expiring<ErrorCatching<A>> a) {
    return a.data().map(a$ -> expiring(a$, a.expiry()));
  }

  public static <A> ErrorCatching<Expiring<A>> join(ErrorCatching<Expiring<ErrorCatching<Expiring<A>>>> a) {
    return ErrorCatchingMonad.map(ErrorCatchingMonad.join(ErrorCatchingMonad.map(a, DynamicsMonad::distribute)), ExpiringMonad::join);
  }

  // Not fully monadic since we intentionally ignore expiry information, but useful nonetheless.

  public static <A extends Dynamics<?, A>> DynamicsEffect<A> effect(Function<A, A> f) {
    return bindEffect(f.andThen(DynamicsMonad::pure));
  }

  public static <A extends Dynamics<?, A>> DynamicsEffect<A> bindEffect(Function<A, ErrorCatching<Expiring<A>>> f) {
    return ea -> ErrorCatchingMonad.bind(ea, a -> f.apply(a.data()));
  }

  // GENERATED CODE START
  // Supplemental methods generated by generate_monad_methods.py on 2023-11-28.
  
  public static <A, B> Function<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>> apply(ErrorCatching<Expiring<Function<A, B>>> f) {
    return a -> apply(a, f);
  }
  
  public static <A, B> ErrorCatching<Expiring<B>> map(ErrorCatching<Expiring<A>> a, Function<A, B> f) {
    return apply(a, pure(f));
  }
  
  public static <A, B> Function<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>> map(Function<A, B> f) {
    return apply(pure(f));
  }
  
  public static <A, B> ErrorCatching<Expiring<B>> bind(ErrorCatching<Expiring<A>> a, Function<A, ErrorCatching<Expiring<B>>> f) {
    return join(map(a, f));
  }
  
  public static <A, B> Function<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>> bind(Function<A, ErrorCatching<Expiring<B>>> f) {
    return a -> bind(a, f);
  }
  
  public static <A, B, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, BiFunction<A, B, Result> function) {
    return map(a, b, curry(function));
  }
  
  public static <A, B, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, Function<A, Function<B, Result>> function) {
    return apply(b, map(a, function));
  }
  
  public static <A, B, Result> BiFunction<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<Result>>> map(BiFunction<A, B, Result> function) {
    return (a, b) -> map(a, b, function);
  }
  
  public static <A, B, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, BiFunction<A, B, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, Function<A, Function<B, ErrorCatching<Expiring<Result>>>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> BiFunction<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<Result>>> bind(BiFunction<A, B, ErrorCatching<Expiring<Result>>> function) {
    return (a, b) -> bind(a, b, function);
  }
  
  public static <A, B, C, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, TriFunction<A, B, C, Result> function) {
    return map(a, b, c, curry(function));
  }
  
  public static <A, B, C, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, Function<A, Function<B, Function<C, Result>>> function) {
    return apply(c, map(a, b, function));
  }
  
  public static <A, B, C, Result> TriFunction<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<Result>>> map(TriFunction<A, B, C, Result> function) {
    return (a, b, c) -> map(a, b, c, function);
  }
  
  public static <A, B, C, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, TriFunction<A, B, C, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, Function<A, Function<B, Function<C, ErrorCatching<Expiring<Result>>>>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> TriFunction<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<Result>>> bind(TriFunction<A, B, C, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c) -> bind(a, b, c, function);
  }
  
  public static <A, B, C, D, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, Function4<A, B, C, D, Result> function) {
    return map(a, b, c, d, curry(function));
  }
  
  public static <A, B, C, D, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, Function<A, Function<B, Function<C, Function<D, Result>>>> function) {
    return apply(d, map(a, b, c, function));
  }
  
  public static <A, B, C, D, Result> Function4<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<Result>>> map(Function4<A, B, C, D, Result> function) {
    return (a, b, c, d) -> map(a, b, c, d, function);
  }
  
  public static <A, B, C, D, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, Function4<A, B, C, D, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, Function<A, Function<B, Function<C, Function<D, ErrorCatching<Expiring<Result>>>>>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> Function4<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<Result>>> bind(Function4<A, B, C, D, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d) -> bind(a, b, c, d, function);
  }
  
  public static <A, B, C, D, E, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, Function5<A, B, C, D, E, Result> function) {
    return map(a, b, c, d, e, curry(function));
  }
  
  public static <A, B, C, D, E, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, Function<A, Function<B, Function<C, Function<D, Function<E, Result>>>>> function) {
    return apply(e, map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<Result>>> map(Function5<A, B, C, D, E, Result> function) {
    return (a, b, c, d, e) -> map(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, Function5<A, B, C, D, E, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, Function<A, Function<B, Function<C, Function<D, Function<E, ErrorCatching<Expiring<Result>>>>>>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<Result>>> bind(Function5<A, B, C, D, E, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e) -> bind(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, F, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, Function6<A, B, C, D, E, F, Result> function) {
    return map(a, b, c, d, e, f, curry(function));
  }
  
  public static <A, B, C, D, E, F, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Result>>>>>> function) {
    return apply(f, map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<Result>>> map(Function6<A, B, C, D, E, F, Result> function) {
    return (a, b, c, d, e, f) -> map(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, Function6<A, B, C, D, E, F, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, ErrorCatching<Expiring<Result>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<Result>>> bind(Function6<A, B, C, D, E, F, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f) -> bind(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, Function7<A, B, C, D, E, F, G, Result> function) {
    return map(a, b, c, d, e, f, g, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Result>>>>>>> function) {
    return apply(g, map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<Result>>> map(Function7<A, B, C, D, E, F, G, Result> function) {
    return (a, b, c, d, e, f, g) -> map(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, Function7<A, B, C, D, E, F, G, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, ErrorCatching<Expiring<Result>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<Result>>> bind(Function7<A, B, C, D, E, F, G, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g) -> bind(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, Function8<A, B, C, D, E, F, G, H, Result> function) {
    return map(a, b, c, d, e, f, g, h, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Result>>>>>>>> function) {
    return apply(h, map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<Result>>> map(Function8<A, B, C, D, E, F, G, H, Result> function) {
    return (a, b, c, d, e, f, g, h) -> map(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, Function8<A, B, C, D, E, F, G, H, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, ErrorCatching<Expiring<Result>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<Result>>> bind(Function8<A, B, C, D, E, F, G, H, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h) -> bind(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Result>>>>>>>>> function) {
    return apply(i, map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<Result>>> map(Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return (a, b, c, d, e, f, g, h, i) -> map(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, Function9<A, B, C, D, E, F, G, H, I, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, ErrorCatching<Expiring<Result>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<Result>>> bind(Function9<A, B, C, D, E, F, G, H, I, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i) -> bind(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Result>>>>>>>>>> function) {
    return apply(j, map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<Result>>> map(Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> map(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, Function10<A, B, C, D, E, F, G, H, I, J, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, ErrorCatching<Expiring<Result>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<Result>>> bind(Function10<A, B, C, D, E, F, G, H, I, J, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> bind(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Result>>>>>>>>>>> function) {
    return apply(k, map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<Result>>> map(Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> map(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, Function11<A, B, C, D, E, F, G, H, I, J, K, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, ErrorCatching<Expiring<Result>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<Result>>> bind(Function11<A, B, C, D, E, F, G, H, I, J, K, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> bind(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Result>>>>>>>>>>>> function) {
    return apply(l, map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<Result>>> map(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> map(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, ErrorCatching<Expiring<Result>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<Result>>> bind(Function12<A, B, C, D, E, F, G, H, I, J, K, L, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Result>>>>>>>>>>>>> function) {
    return apply(m, map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<Result>>> map(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, ErrorCatching<Expiring<Result>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<Result>>> bind(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Result>>>>>>>>>>>>>> function) {
    return apply(n, map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<Result>>> map(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, ErrorCatching<Expiring<Result>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<Result>>> bind(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Result>>>>>>>>>>>>>>> function) {
    return apply(o, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<Result>>> map(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, ErrorCatching<Expiring<Result>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<Result>>> bind(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Result>>>>>>>>>>>>>>>> function) {
    return apply(p, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Result>>> map(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, ErrorCatching<Expiring<Result>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Result>>> bind(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Result>>>>>>>>>>>>>>>>> function) {
    return apply(q, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Q>>, ErrorCatching<Expiring<Result>>> map(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, ErrorCatching<Expiring<Result>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Q>>, ErrorCatching<Expiring<Result>>> bind(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Result>>>>>>>>>>>>>>>>>> function) {
    return apply(r, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Q>>, ErrorCatching<Expiring<R>>, ErrorCatching<Expiring<Result>>> map(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, ErrorCatching<Expiring<Result>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Q>>, ErrorCatching<Expiring<R>>, ErrorCatching<Expiring<Result>>> bind(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, ErrorCatching<Expiring<S>> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, ErrorCatching<Expiring<S>> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Result>>>>>>>>>>>>>>>>>>> function) {
    return apply(s, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Q>>, ErrorCatching<Expiring<R>>, ErrorCatching<Expiring<S>>, ErrorCatching<Expiring<Result>>> map(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, ErrorCatching<Expiring<S>> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, ErrorCatching<Expiring<S>> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, ErrorCatching<Expiring<Result>>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Q>>, ErrorCatching<Expiring<R>>, ErrorCatching<Expiring<S>>, ErrorCatching<Expiring<Result>>> bind(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, ErrorCatching<Expiring<S>> s, ErrorCatching<Expiring<T>> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ErrorCatching<Expiring<Result>> map(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, ErrorCatching<Expiring<S>> s, ErrorCatching<Expiring<T>> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Result>>>>>>>>>>>>>>>>>>>> function) {
    return apply(t, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Q>>, ErrorCatching<Expiring<R>>, ErrorCatching<Expiring<S>>, ErrorCatching<Expiring<T>>, ErrorCatching<Expiring<Result>>> map(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, ErrorCatching<Expiring<S>> s, ErrorCatching<Expiring<T>> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ErrorCatching<Expiring<Result>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ErrorCatching<Expiring<Result>> bind(ErrorCatching<Expiring<A>> a, ErrorCatching<Expiring<B>> b, ErrorCatching<Expiring<C>> c, ErrorCatching<Expiring<D>> d, ErrorCatching<Expiring<E>> e, ErrorCatching<Expiring<F>> f, ErrorCatching<Expiring<G>> g, ErrorCatching<Expiring<H>> h, ErrorCatching<Expiring<I>> i, ErrorCatching<Expiring<J>> j, ErrorCatching<Expiring<K>> k, ErrorCatching<Expiring<L>> l, ErrorCatching<Expiring<M>> m, ErrorCatching<Expiring<N>> n, ErrorCatching<Expiring<O>> o, ErrorCatching<Expiring<P>> p, ErrorCatching<Expiring<Q>> q, ErrorCatching<Expiring<R>> r, ErrorCatching<Expiring<S>> s, ErrorCatching<Expiring<T>> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, ErrorCatching<Expiring<Result>>>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ErrorCatching<Expiring<A>>, ErrorCatching<Expiring<B>>, ErrorCatching<Expiring<C>>, ErrorCatching<Expiring<D>>, ErrorCatching<Expiring<E>>, ErrorCatching<Expiring<F>>, ErrorCatching<Expiring<G>>, ErrorCatching<Expiring<H>>, ErrorCatching<Expiring<I>>, ErrorCatching<Expiring<J>>, ErrorCatching<Expiring<K>>, ErrorCatching<Expiring<L>>, ErrorCatching<Expiring<M>>, ErrorCatching<Expiring<N>>, ErrorCatching<Expiring<O>>, ErrorCatching<Expiring<P>>, ErrorCatching<Expiring<Q>>, ErrorCatching<Expiring<R>>, ErrorCatching<Expiring<S>>, ErrorCatching<Expiring<T>>, ErrorCatching<Expiring<Result>>> bind(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ErrorCatching<Expiring<Result>>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  // GENERATED CODE END
}
