package gov.nasa.jpl.aerie.contrib.streamline.core.monads;

import gov.nasa.jpl.aerie.contrib.streamline.core.ErrorCatching;
import gov.nasa.jpl.aerie.contrib.streamline.utils.*;
import org.apache.commons.lang3.function.TriFunction;

import java.util.function.BiFunction;
import java.util.function.Function;

import static gov.nasa.jpl.aerie.contrib.streamline.core.ErrorCatching.failure;
import static gov.nasa.jpl.aerie.contrib.streamline.core.ErrorCatching.success;
import static gov.nasa.jpl.aerie.contrib.streamline.utils.FunctionalUtils.curry;
import static java.util.function.Function.identity;

public final class ErrorCatchingMonad {
  private ErrorCatchingMonad() {}

  public static <A> ErrorCatching<A> pure(A a) {
    return success(a);
  }

  public static <A, B> ErrorCatching<B> apply(ErrorCatching<A> a, ErrorCatching<Function<A, B>> f) {
    return f.match(f$ -> a.match(a$ -> {
      try {
        return success(f$.apply(a$));
      } catch (Throwable e) {
        return failure(e);
      }
    }, ErrorCatching::failure), ErrorCatching::failure);
  }

  public static <A> ErrorCatching<A> join(ErrorCatching<ErrorCatching<A>> a) {
    return a.match(identity(), ErrorCatching::failure);
  }

  // GENERATED CODE START
  // Supplemental methods generated by generate_monad_methods.py on 2023-12-06.
  
  public static <A, B> Function<ErrorCatching<A>, ErrorCatching<B>> apply(ErrorCatching<Function<A, B>> f) {
    return a -> apply(a, f);
  }
  
  public static <A, B> ErrorCatching<B> map(ErrorCatching<A> a, Function<A, B> f) {
    return apply(a, pure(f));
  }
  
  public static <A, B> Function<ErrorCatching<A>, ErrorCatching<B>> map(Function<A, B> f) {
    return apply(pure(f));
  }
  
  public static <A, B> ErrorCatching<B> bind(ErrorCatching<A> a, Function<A, ErrorCatching<B>> f) {
    return join(map(a, f));
  }
  
  public static <A, B> Function<ErrorCatching<A>, ErrorCatching<B>> bind(Function<A, ErrorCatching<B>> f) {
    return a -> bind(a, f);
  }
  
  public static <A, B, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, BiFunction<A, B, Result> function) {
    return map(a, b, curry(function));
  }
  
  public static <A, B, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, Function<A, Function<B, Result>> function) {
    return apply(b, map(a, function));
  }
  
  public static <A, B, Result> BiFunction<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<Result>> map(BiFunction<A, B, Result> function) {
    return (a, b) -> map(a, b, function);
  }
  
  public static <A, B, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, BiFunction<A, B, ErrorCatching<Result>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, Function<A, Function<B, ErrorCatching<Result>>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> BiFunction<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<Result>> bind(BiFunction<A, B, ErrorCatching<Result>> function) {
    return (a, b) -> bind(a, b, function);
  }
  
  public static <A, B, C, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, TriFunction<A, B, C, Result> function) {
    return map(a, b, c, curry(function));
  }
  
  public static <A, B, C, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, Function<A, Function<B, Function<C, Result>>> function) {
    return apply(c, map(a, b, function));
  }
  
  public static <A, B, C, Result> TriFunction<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<Result>> map(TriFunction<A, B, C, Result> function) {
    return (a, b, c) -> map(a, b, c, function);
  }
  
  public static <A, B, C, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, TriFunction<A, B, C, ErrorCatching<Result>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, Function<A, Function<B, Function<C, ErrorCatching<Result>>>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> TriFunction<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<Result>> bind(TriFunction<A, B, C, ErrorCatching<Result>> function) {
    return (a, b, c) -> bind(a, b, c, function);
  }
  
  public static <A, B, C, D, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, Function4<A, B, C, D, Result> function) {
    return map(a, b, c, d, curry(function));
  }
  
  public static <A, B, C, D, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, Function<A, Function<B, Function<C, Function<D, Result>>>> function) {
    return apply(d, map(a, b, c, function));
  }
  
  public static <A, B, C, D, Result> Function4<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<Result>> map(Function4<A, B, C, D, Result> function) {
    return (a, b, c, d) -> map(a, b, c, d, function);
  }
  
  public static <A, B, C, D, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, Function4<A, B, C, D, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, Function<A, Function<B, Function<C, Function<D, ErrorCatching<Result>>>>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> Function4<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<Result>> bind(Function4<A, B, C, D, ErrorCatching<Result>> function) {
    return (a, b, c, d) -> bind(a, b, c, d, function);
  }
  
  public static <A, B, C, D, E, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, Function5<A, B, C, D, E, Result> function) {
    return map(a, b, c, d, e, curry(function));
  }
  
  public static <A, B, C, D, E, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, Result>>>>> function) {
    return apply(e, map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<Result>> map(Function5<A, B, C, D, E, Result> function) {
    return (a, b, c, d, e) -> map(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, Function5<A, B, C, D, E, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, ErrorCatching<Result>>>>>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<Result>> bind(Function5<A, B, C, D, E, ErrorCatching<Result>> function) {
    return (a, b, c, d, e) -> bind(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, F, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, Function6<A, B, C, D, E, F, Result> function) {
    return map(a, b, c, d, e, f, curry(function));
  }
  
  public static <A, B, C, D, E, F, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Result>>>>>> function) {
    return apply(f, map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<Result>> map(Function6<A, B, C, D, E, F, Result> function) {
    return (a, b, c, d, e, f) -> map(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, Function6<A, B, C, D, E, F, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, ErrorCatching<Result>>>>>>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<Result>> bind(Function6<A, B, C, D, E, F, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f) -> bind(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, Function7<A, B, C, D, E, F, G, Result> function) {
    return map(a, b, c, d, e, f, g, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Result>>>>>>> function) {
    return apply(g, map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<Result>> map(Function7<A, B, C, D, E, F, G, Result> function) {
    return (a, b, c, d, e, f, g) -> map(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, Function7<A, B, C, D, E, F, G, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, ErrorCatching<Result>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<Result>> bind(Function7<A, B, C, D, E, F, G, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g) -> bind(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, Function8<A, B, C, D, E, F, G, H, Result> function) {
    return map(a, b, c, d, e, f, g, h, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Result>>>>>>>> function) {
    return apply(h, map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<Result>> map(Function8<A, B, C, D, E, F, G, H, Result> function) {
    return (a, b, c, d, e, f, g, h) -> map(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, Function8<A, B, C, D, E, F, G, H, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, ErrorCatching<Result>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<Result>> bind(Function8<A, B, C, D, E, F, G, H, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h) -> bind(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Result>>>>>>>>> function) {
    return apply(i, map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<Result>> map(Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return (a, b, c, d, e, f, g, h, i) -> map(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, Function9<A, B, C, D, E, F, G, H, I, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, ErrorCatching<Result>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<Result>> bind(Function9<A, B, C, D, E, F, G, H, I, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i) -> bind(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Result>>>>>>>>>> function) {
    return apply(j, map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<Result>> map(Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> map(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, Function10<A, B, C, D, E, F, G, H, I, J, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, ErrorCatching<Result>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<Result>> bind(Function10<A, B, C, D, E, F, G, H, I, J, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> bind(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Result>>>>>>>>>>> function) {
    return apply(k, map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<Result>> map(Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> map(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, ErrorCatching<Result>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<Result>> bind(Function11<A, B, C, D, E, F, G, H, I, J, K, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> bind(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Result>>>>>>>>>>>> function) {
    return apply(l, map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<Result>> map(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> map(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, ErrorCatching<Result>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<Result>> bind(Function12<A, B, C, D, E, F, G, H, I, J, K, L, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Result>>>>>>>>>>>>> function) {
    return apply(m, map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<Result>> map(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, ErrorCatching<Result>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<Result>> bind(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Result>>>>>>>>>>>>>> function) {
    return apply(n, map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<Result>> map(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, ErrorCatching<Result>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<Result>> bind(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Result>>>>>>>>>>>>>>> function) {
    return apply(o, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<Result>> map(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, ErrorCatching<Result>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<Result>> bind(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Result>>>>>>>>>>>>>>>> function) {
    return apply(p, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Result>> map(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, ErrorCatching<Result>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Result>> bind(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Result>>>>>>>>>>>>>>>>> function) {
    return apply(q, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Q>, ErrorCatching<Result>> map(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, ErrorCatching<Result>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Q>, ErrorCatching<Result>> bind(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Result>>>>>>>>>>>>>>>>>> function) {
    return apply(r, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Q>, ErrorCatching<R>, ErrorCatching<Result>> map(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, ErrorCatching<Result>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Q>, ErrorCatching<R>, ErrorCatching<Result>> bind(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, ErrorCatching<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, ErrorCatching<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Result>>>>>>>>>>>>>>>>>>> function) {
    return apply(s, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Q>, ErrorCatching<R>, ErrorCatching<S>, ErrorCatching<Result>> map(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, ErrorCatching<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, ErrorCatching<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, ErrorCatching<Result>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Q>, ErrorCatching<R>, ErrorCatching<S>, ErrorCatching<Result>> bind(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, ErrorCatching<S> s, ErrorCatching<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ErrorCatching<Result> map(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, ErrorCatching<S> s, ErrorCatching<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Result>>>>>>>>>>>>>>>>>>>> function) {
    return apply(t, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Q>, ErrorCatching<R>, ErrorCatching<S>, ErrorCatching<T>, ErrorCatching<Result>> map(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, ErrorCatching<S> s, ErrorCatching<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ErrorCatching<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ErrorCatching<Result> bind(ErrorCatching<A> a, ErrorCatching<B> b, ErrorCatching<C> c, ErrorCatching<D> d, ErrorCatching<E> e, ErrorCatching<F> f, ErrorCatching<G> g, ErrorCatching<H> h, ErrorCatching<I> i, ErrorCatching<J> j, ErrorCatching<K> k, ErrorCatching<L> l, ErrorCatching<M> m, ErrorCatching<N> n, ErrorCatching<O> o, ErrorCatching<P> p, ErrorCatching<Q> q, ErrorCatching<R> r, ErrorCatching<S> s, ErrorCatching<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, ErrorCatching<Result>>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ErrorCatching<A>, ErrorCatching<B>, ErrorCatching<C>, ErrorCatching<D>, ErrorCatching<E>, ErrorCatching<F>, ErrorCatching<G>, ErrorCatching<H>, ErrorCatching<I>, ErrorCatching<J>, ErrorCatching<K>, ErrorCatching<L>, ErrorCatching<M>, ErrorCatching<N>, ErrorCatching<O>, ErrorCatching<P>, ErrorCatching<Q>, ErrorCatching<R>, ErrorCatching<S>, ErrorCatching<T>, ErrorCatching<Result>> bind(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ErrorCatching<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  // GENERATED CODE END
}
