package gov.nasa.jpl.aerie.contrib.streamline.core.monads;

import gov.nasa.jpl.aerie.contrib.streamline.core.ThinResource;
import gov.nasa.jpl.aerie.contrib.streamline.utils.*;
import org.apache.commons.lang3.function.TriFunction;

import java.util.function.BiFunction;
import java.util.function.Function;

import static gov.nasa.jpl.aerie.contrib.streamline.utils.FunctionalUtils.curry;

public final class ThinResourceMonad {
  private ThinResourceMonad() {}

  public static <A> ThinResource<A> pure(A a) {
    return () -> a;
  }

  public static <A, B> ThinResource<B> apply(ThinResource<A> a, ThinResource<Function<A, B>> f) {
    return () -> f.getDynamics().apply(a.getDynamics());
  }

  public static <A> ThinResource<A> join(ThinResource<ThinResource<A>> a) {
    return () -> a.getDynamics().getDynamics();
  }

  // GENERATED CODE START
  // Supplemental methods generated by generate_monad_methods.py on 2023-12-06.
  
  public static <A, B> Function<ThinResource<A>, ThinResource<B>> apply(ThinResource<Function<A, B>> f) {
    return a -> apply(a, f);
  }
  
  public static <A, B> ThinResource<B> map(ThinResource<A> a, Function<A, B> f) {
    return apply(a, pure(f));
  }
  
  public static <A, B> Function<ThinResource<A>, ThinResource<B>> map(Function<A, B> f) {
    return apply(pure(f));
  }
  
  public static <A, B> ThinResource<B> bind(ThinResource<A> a, Function<A, ThinResource<B>> f) {
    return join(map(a, f));
  }
  
  public static <A, B> Function<ThinResource<A>, ThinResource<B>> bind(Function<A, ThinResource<B>> f) {
    return a -> bind(a, f);
  }
  
  public static <A, B, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, BiFunction<A, B, Result> function) {
    return map(a, b, curry(function));
  }
  
  public static <A, B, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, Function<A, Function<B, Result>> function) {
    return apply(b, map(a, function));
  }
  
  public static <A, B, Result> BiFunction<ThinResource<A>, ThinResource<B>, ThinResource<Result>> map(BiFunction<A, B, Result> function) {
    return (a, b) -> map(a, b, function);
  }
  
  public static <A, B, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, BiFunction<A, B, ThinResource<Result>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, Function<A, Function<B, ThinResource<Result>>> function) {
    return join(map(a, b, function));
  }
  
  public static <A, B, Result> BiFunction<ThinResource<A>, ThinResource<B>, ThinResource<Result>> bind(BiFunction<A, B, ThinResource<Result>> function) {
    return (a, b) -> bind(a, b, function);
  }
  
  public static <A, B, C, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, TriFunction<A, B, C, Result> function) {
    return map(a, b, c, curry(function));
  }
  
  public static <A, B, C, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, Function<A, Function<B, Function<C, Result>>> function) {
    return apply(c, map(a, b, function));
  }
  
  public static <A, B, C, Result> TriFunction<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<Result>> map(TriFunction<A, B, C, Result> function) {
    return (a, b, c) -> map(a, b, c, function);
  }
  
  public static <A, B, C, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, TriFunction<A, B, C, ThinResource<Result>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, Function<A, Function<B, Function<C, ThinResource<Result>>>> function) {
    return join(map(a, b, c, function));
  }
  
  public static <A, B, C, Result> TriFunction<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<Result>> bind(TriFunction<A, B, C, ThinResource<Result>> function) {
    return (a, b, c) -> bind(a, b, c, function);
  }
  
  public static <A, B, C, D, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, Function4<A, B, C, D, Result> function) {
    return map(a, b, c, d, curry(function));
  }
  
  public static <A, B, C, D, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, Function<A, Function<B, Function<C, Function<D, Result>>>> function) {
    return apply(d, map(a, b, c, function));
  }
  
  public static <A, B, C, D, Result> Function4<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<Result>> map(Function4<A, B, C, D, Result> function) {
    return (a, b, c, d) -> map(a, b, c, d, function);
  }
  
  public static <A, B, C, D, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, Function4<A, B, C, D, ThinResource<Result>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, Function<A, Function<B, Function<C, Function<D, ThinResource<Result>>>>> function) {
    return join(map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, Result> Function4<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<Result>> bind(Function4<A, B, C, D, ThinResource<Result>> function) {
    return (a, b, c, d) -> bind(a, b, c, d, function);
  }
  
  public static <A, B, C, D, E, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, Function5<A, B, C, D, E, Result> function) {
    return map(a, b, c, d, e, curry(function));
  }
  
  public static <A, B, C, D, E, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, Result>>>>> function) {
    return apply(e, map(a, b, c, d, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<Result>> map(Function5<A, B, C, D, E, Result> function) {
    return (a, b, c, d, e) -> map(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, Function5<A, B, C, D, E, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, Function<A, Function<B, Function<C, Function<D, Function<E, ThinResource<Result>>>>>> function) {
    return join(map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, Result> Function5<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<Result>> bind(Function5<A, B, C, D, E, ThinResource<Result>> function) {
    return (a, b, c, d, e) -> bind(a, b, c, d, e, function);
  }
  
  public static <A, B, C, D, E, F, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, Function6<A, B, C, D, E, F, Result> function) {
    return map(a, b, c, d, e, f, curry(function));
  }
  
  public static <A, B, C, D, E, F, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Result>>>>>> function) {
    return apply(f, map(a, b, c, d, e, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<Result>> map(Function6<A, B, C, D, E, F, Result> function) {
    return (a, b, c, d, e, f) -> map(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, Function6<A, B, C, D, E, F, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, ThinResource<Result>>>>>>> function) {
    return join(map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, Result> Function6<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<Result>> bind(Function6<A, B, C, D, E, F, ThinResource<Result>> function) {
    return (a, b, c, d, e, f) -> bind(a, b, c, d, e, f, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, Function7<A, B, C, D, E, F, G, Result> function) {
    return map(a, b, c, d, e, f, g, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Result>>>>>>> function) {
    return apply(g, map(a, b, c, d, e, f, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<Result>> map(Function7<A, B, C, D, E, F, G, Result> function) {
    return (a, b, c, d, e, f, g) -> map(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, Function7<A, B, C, D, E, F, G, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, ThinResource<Result>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, Result> Function7<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<Result>> bind(Function7<A, B, C, D, E, F, G, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g) -> bind(a, b, c, d, e, f, g, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, Function8<A, B, C, D, E, F, G, H, Result> function) {
    return map(a, b, c, d, e, f, g, h, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Result>>>>>>>> function) {
    return apply(h, map(a, b, c, d, e, f, g, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<Result>> map(Function8<A, B, C, D, E, F, G, H, Result> function) {
    return (a, b, c, d, e, f, g, h) -> map(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, Function8<A, B, C, D, E, F, G, H, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, ThinResource<Result>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, Result> Function8<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<Result>> bind(Function8<A, B, C, D, E, F, G, H, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h) -> bind(a, b, c, d, e, f, g, h, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Result>>>>>>>>> function) {
    return apply(i, map(a, b, c, d, e, f, g, h, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<Result>> map(Function9<A, B, C, D, E, F, G, H, I, Result> function) {
    return (a, b, c, d, e, f, g, h, i) -> map(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, Function9<A, B, C, D, E, F, G, H, I, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, ThinResource<Result>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, Result> Function9<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<Result>> bind(Function9<A, B, C, D, E, F, G, H, I, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i) -> bind(a, b, c, d, e, f, g, h, i, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Result>>>>>>>>>> function) {
    return apply(j, map(a, b, c, d, e, f, g, h, i, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<Result>> map(Function10<A, B, C, D, E, F, G, H, I, J, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> map(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, Function10<A, B, C, D, E, F, G, H, I, J, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, ThinResource<Result>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, Result> Function10<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<Result>> bind(Function10<A, B, C, D, E, F, G, H, I, J, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j) -> bind(a, b, c, d, e, f, g, h, i, j, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Result>>>>>>>>>>> function) {
    return apply(k, map(a, b, c, d, e, f, g, h, i, j, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<Result>> map(Function11<A, B, C, D, E, F, G, H, I, J, K, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> map(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, Function11<A, B, C, D, E, F, G, H, I, J, K, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, ThinResource<Result>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, Result> Function11<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<Result>> bind(Function11<A, B, C, D, E, F, G, H, I, J, K, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k) -> bind(a, b, c, d, e, f, g, h, i, j, k, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Result>>>>>>>>>>>> function) {
    return apply(l, map(a, b, c, d, e, f, g, h, i, j, k, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<Result>> map(Function12<A, B, C, D, E, F, G, H, I, J, K, L, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> map(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, Function12<A, B, C, D, E, F, G, H, I, J, K, L, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, ThinResource<Result>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, Result> Function12<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<Result>> bind(Function12<A, B, C, D, E, F, G, H, I, J, K, L, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Result>>>>>>>>>>>>> function) {
    return apply(m, map(a, b, c, d, e, f, g, h, i, j, k, l, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<Result>> map(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, ThinResource<Result>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, Result> Function13<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<Result>> bind(Function13<A, B, C, D, E, F, G, H, I, J, K, L, M, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Result>>>>>>>>>>>>>> function) {
    return apply(n, map(a, b, c, d, e, f, g, h, i, j, k, l, m, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<Result>> map(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, ThinResource<Result>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, Result> Function14<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<Result>> bind(Function14<A, B, C, D, E, F, G, H, I, J, K, L, M, N, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Result>>>>>>>>>>>>>>> function) {
    return apply(o, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<Result>> map(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, ThinResource<Result>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> Function15<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<Result>> bind(Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Result>>>>>>>>>>>>>>>> function) {
    return apply(p, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Result>> map(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, ThinResource<Result>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Result> Function16<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Result>> bind(Function16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Result>>>>>>>>>>>>>>>>> function) {
    return apply(q, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Q>, ThinResource<Result>> map(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, ThinResource<Result>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, Result> Function17<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Q>, ThinResource<Result>> bind(Function17<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Result>>>>>>>>>>>>>>>>>> function) {
    return apply(r, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Q>, ThinResource<R>, ThinResource<Result>> map(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, ThinResource<Result>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, Result> Function18<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Q>, ThinResource<R>, ThinResource<Result>> bind(Function18<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, ThinResource<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, ThinResource<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Result>>>>>>>>>>>>>>>>>>> function) {
    return apply(s, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Q>, ThinResource<R>, ThinResource<S>, ThinResource<Result>> map(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, ThinResource<S> s, Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, ThinResource<S> s, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, ThinResource<Result>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, Result> Function19<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Q>, ThinResource<R>, ThinResource<S>, ThinResource<Result>> bind(Function19<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, ThinResource<S> s, ThinResource<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, curry(function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ThinResource<Result> map(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, ThinResource<S> s, ThinResource<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, Result>>>>>>>>>>>>>>>>>>>> function) {
    return apply(t, map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Q>, ThinResource<R>, ThinResource<S>, ThinResource<T>, ThinResource<Result>> map(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, ThinResource<S> s, ThinResource<T> t, Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ThinResource<Result>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> ThinResource<Result> bind(ThinResource<A> a, ThinResource<B> b, ThinResource<C> c, ThinResource<D> d, ThinResource<E> e, ThinResource<F> f, ThinResource<G> g, ThinResource<H> h, ThinResource<I> i, ThinResource<J> j, ThinResource<K> k, ThinResource<L> l, ThinResource<M> m, ThinResource<N> n, ThinResource<O> o, ThinResource<P> p, ThinResource<Q> q, ThinResource<R> r, ThinResource<S> s, ThinResource<T> t, Function<A, Function<B, Function<C, Function<D, Function<E, Function<F, Function<G, Function<H, Function<I, Function<J, Function<K, Function<L, Function<M, Function<N, Function<O, Function<P, Function<Q, Function<R, Function<S, Function<T, ThinResource<Result>>>>>>>>>>>>>>>>>>>>> function) {
    return join(map(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function));
  }
  
  public static <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, Result> Function20<ThinResource<A>, ThinResource<B>, ThinResource<C>, ThinResource<D>, ThinResource<E>, ThinResource<F>, ThinResource<G>, ThinResource<H>, ThinResource<I>, ThinResource<J>, ThinResource<K>, ThinResource<L>, ThinResource<M>, ThinResource<N>, ThinResource<O>, ThinResource<P>, ThinResource<Q>, ThinResource<R>, ThinResource<S>, ThinResource<T>, ThinResource<Result>> bind(Function20<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, ThinResource<Result>> function) {
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) -> bind(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, function);
  }
  // GENERATED CODE END
}
