package gov.nasa.jpl.aerie.contrib.streamline.utils;

/**
 * 7-argument function.
 *
 * Generated by generate_functional_utils.py on 2023-11-28.
 */
public interface Function7<A, B, C, D, E, F, G, Result> {
    Result apply(A a, B b, C c, D d, E e, F f, G g);
}