package gov.nasa.jpl.aerie.contrib.streamline.utils;

/**
 * 15-argument function.
 *
 * Generated by generate_functional_utils.py on 2023-11-28.
 */
public interface Function15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, Result> {
    Result apply(A a, B b, C c, D d, E e, F f, G g, H h, I i, J j, K k, L l, M m, N n, O o);
}