# PlanDev 4.3.x -> 4.4.x binary package renames
#
# Intended for existing Mission Model, procedural constraint, and
# procedural scheduling goal JARs that cannot easily be rebuilt from source.
#
# call with:
# java -jar /path/to/org.eclipse.transformer.cli-1.0.0.jar original.jar transformed.jar \
#  -tr plandev-4.4-renames.properties


gov.nasa.jpl.aerie.merlin.protocol=gov.nasa.ammos.plandev.merlin.protocol
gov.nasa.jpl.aerie.merlin.protocol.*=gov.nasa.ammos.plandev.merlin.protocol

gov.nasa.jpl.aerie.types=gov.nasa.ammos.plandev.types
gov.nasa.jpl.aerie.types.*=gov.nasa.ammos.plandev.types

gov.nasa.ammos.aerie.procedural.constraints=gov.nasa.ammos.plandev.procedural.constraints
gov.nasa.ammos.aerie.procedural.constraints.*=gov.nasa.ammos.plandev.procedural.constraints

gov.nasa.ammos.aerie.procedural.scheduling=gov.nasa.ammos.plandev.procedural.scheduling
gov.nasa.ammos.aerie.procedural.scheduling.*=gov.nasa.ammos.plandev.procedural.scheduling

gov.nasa.ammos.aerie.procedural.timeline=gov.nasa.ammos.plandev.procedural.timeline
gov.nasa.ammos.aerie.procedural.timeline.*=gov.nasa.ammos.plandev.procedural.timeline

gov.nasa.ammos.aerie.procedural.utils=gov.nasa.ammos.plandev.procedural.utils
gov.nasa.ammos.aerie.procedural.utils.*=gov.nasa.ammos.plandev.procedural.utils
