apiVersion: v1
kind: Service
metadata:
  namespace: plandev-dev
  name: plandev-action
spec:
  ports:
    - name: "27186"
      port: 27186
      targetPort: 27186
  selector:
    app: plandev-action
