apiVersion: v1
kind: Service
metadata:
  namespace: plandev-dev
  name: plandev-merlin
spec:
  ports:
    - name: "27183"
      port: 27183
      targetPort: 27183
  selector:
    app: plandev-merlin
