apiVersion: v1
kind: Service
metadata:
  namespace: plandev-dev
  name: plandev-sequencing
spec:
  ports:
    - name: "27184"
      port: 27184
      targetPort: 27184
  selector:
    app: plandev-sequencing
