apiVersion: v1
kind: Service
metadata:
  namespace: plandev-dev
  name: plandev-scheduler
spec:
  ports:
    - name: "27185"
      port: 27185
      targetPort: 27185
  selector:
    app: plandev-scheduler
