apiVersion: v1
kind: Service
metadata:
  namespace: plandev-dev
  name: plandev-workspace
spec:
  selector:
    app: plandev-workspace
  ports:
    - name: "28000"
      port: 28000
      targetPort: 28000
