apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: plandev-dev
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: ghcr.io/nasa-ammos/plandev-postgres:develop
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: PLANDEV_DB
              value: plandev
            - name: PLANDEV_METADATA_DB
              value: plandev_hasura
          envFrom:
            - secretRef:
                name: dev-env
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
