java_library(
    name = "banananation",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**/*"]),
    resources_root = "src/main/resources/",
    deps = [
        "//third-party:commons-lang3",
        "//third-party:JNISpice",
        "//merlin-sdk:merlin-sdk",
    ],
    annotation_processors = ["gov.nasa.jpl.ammos.mpsa.aerie.merlinsdk.processor.ActivityProcessor"],
    annotation_processor_deps = ["//merlin-sdk:merlin-sdk"]
)
