java_library(
    name = "banananation",
    srcs = [],
    resources = glob(["src/main/resources/**/*"]),
    resources_root = "src/main/resources/",
    exported_deps = [
        "//third-party/banananation/core:banananation",
        "//third-party:JNISpice",
        "//merlin-sdk:merlin-sdk",
    ],
    annotation_processors = ["gov.nasa.jpl.ammos.mpsa.aerie.merlinsdk.processor.ActivityProcessor"],
    annotation_processor_deps = ["//merlin-sdk:merlin-sdk"]
)

java_test(
    name = "test",
    srcs = [],
    resources = glob(["src/test/resources/**/*"]),
    resources_root = "src/test/resources/",
    deps = [
        # Third Party
        "//third-party/banananation/test:banananation",
        # Aerie
        ":banananation"
    ]
)
