-- Create table for external events
create table merlin.external_event (
    id integer generated by default as identity,
    key text not null,
    event_type_name text not null,
    source_id integer not null,
    start_time timestamp with time zone not null,
    duration interval not null,
    properties jsonb,

    constraint external_event_pkey
      primary key (id),
    constraint external_event_references_source_id
      foreign key (source_id)
      references merlin.external_source(id),
    constraint external_event_references_event_type_name
      foreign key (event_type_name)
      references merlin.external_event_type(name),
    constraint external_event_logical_identifiers
      unique (key, source_id, event_type_name)
);

comment on table merlin.external_event is e''
  'A table for externally imported events.';
comment on constraint external_event_logical_identifiers on merlin.external_event is e''
  'The tuple (key, event_type_name, and source_id) must be unique!';
