java_library(
    name = "sample-adaptation",
    srcs = glob(["src/main/java/**/*.java"]),
    extra_arguments = [
        "--source-path", "sample-adaptation/src/",
        "--module-path", "third-party/"
        ],
    deps = [
        "//third-party:commons-io",
        "//third-party:JNISpice",
        "//third-party:junit",

        # Modules
        "//merlin-sdk:merlin-sdk",
        "//merlin-multimission-models:merlin-multimission-models"
    ],
    visibility = ['PUBLIC']
)
