package gov.nasa.jpl.aerie.scheduler.server.services;

import gov.nasa.jpl.aerie.merlin.driver.MissionModel;
import gov.nasa.jpl.aerie.merlin.driver.MissionModelLoader;
import gov.nasa.jpl.aerie.merlin.protocol.types.SerializedValue;
import gov.nasa.jpl.aerie.scheduler.server.exceptions.NoSuchSpecificationException;
import gov.nasa.jpl.aerie.scheduler.GlobalConstraint;
import gov.nasa.jpl.aerie.scheduler.Goal;
import gov.nasa.jpl.aerie.scheduler.HuginnConfiguration;
import gov.nasa.jpl.aerie.scheduler.JarClassLoader;
import gov.nasa.jpl.aerie.scheduler.Plan;
import gov.nasa.jpl.aerie.scheduler.PrioritySolver;
import gov.nasa.jpl.aerie.scheduler.Problem;
import gov.nasa.jpl.aerie.scheduler.Solver;
import gov.nasa.jpl.aerie.scheduler.server.ResultsProtocol;
import gov.nasa.jpl.aerie.scheduler.server.config.PlanOutputMode;
import gov.nasa.jpl.aerie.scheduler.server.exceptions.ResultsProtocolFailure;
import gov.nasa.jpl.aerie.scheduler.server.models.PlanMetadata;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.nio.file.Path;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * agent that handles posed scheduling requests by blocking the requester thread until scheduling is complete
 *
 * @param merlinService interface for querying plan details from merlin
 * @param modelJarsDir path to parent directory for mission model jars (interim backdoor jar file access)
 * @param rulesJarPath path to jar file to load scheduling rules from (interim solution for user input rules)
 * @param outputMode how the scheduling output should be returned to aerie (eg overwrite or new container)
 */
//TODO: will eventually need scheduling goal service arg to pull goals from scheduler's own data store
public record SynchronousSchedulerAgent(
    SpecificationService specificationService,
    GraphQLMerlinService merlinService,
    Path modelJarsDir,
    Path rulesJarPath,
    PlanOutputMode outputMode
)
    implements SchedulerAgent
{
  public SynchronousSchedulerAgent {
    Objects.requireNonNull(merlinService);
    Objects.requireNonNull(modelJarsDir);
    Objects.requireNonNull(rulesJarPath);
  }

  /**
   * {@inheritDoc}
   *
   * consumes any ResultsProtocolFailure exception generated by the scheduling process and writes its message as a
   * failure reason to the given output port (eg aerie could not be reached, mission model could not be loaded from jar
   * file, requested plan revision has changed in the database, scheduler could not find a solution, etc)
   *
   * any remaining exceptions passed upward represent fatal service configuration problems
   */
  @Override
  public void schedule(final ScheduleRequest request, final ResultsProtocol.WriterRole writer) {
    try {
      //confirm requested plan to schedule from/into still exists at targeted version (request could be stale)
      //TODO: maybe some kind of high level db transaction wrapping entire read/update of target plan revision
      ensureRequestIsCurrent(request);

      // TODO Adrien: complete this stubbed block
//      //create scheduler problem seeded with initial plan
//      final var problem = createProblem(planMetadata);
//      final var scheduler = createScheduler(planMetadata, problem);
//
//      //run the scheduler to find a solution to the posed problem, if any
//      final var solutionPlan = scheduler.getNextSolution().orElseThrow(
//          () -> new ResultsProtocolFailure("scheduler returned no solution"));
//
//      //store the solution plan back into merlin (and reconfirm no intervening mods!)
//      //TODO: make revision confirmation atomic part of plan mutation (plan might have been modified during scheduling!)
//      ensureRequestIsCurrent(request);
//      storeFinalPlan(planMetadata, problem.getMissionModel(), solutionPlan);
//
//      //collect results and notify subscribers of success
//      final var results = collectResults(solutionPlan);
//      writer.succeedWith(results);
      writer.failWith("Not yet implemented"); // TODO Adrien: complete this stubbed block
    } catch (final ResultsProtocolFailure | NoSuchSpecificationException e) {
      //unwrap failure message from any anticipated exceptions and forward to subscribers
      writer.failWith(e.getMessage());
    }
  }

  /**
   * confirms that specification revision still matches that expected by the scheduling request
   *
   * @param request the original request for scheduling, containing an intended starting specification revision
   * @throws ResultsProtocolFailure when the requested specification revision does not match the actual revision
   */
  private void ensureRequestIsCurrent(final ScheduleRequest request) throws NoSuchSpecificationException {
    final var currentRevisionData = specificationService.getSpecificationRevisionData(request.specificationId());
    if (currentRevisionData.matches(request.specificationRev()) instanceof final RevisionData.MatchResult.Failure failure) {
      throw new ResultsProtocolFailure("schedule specification with id %s is stale: %s".formatted(
          request.specificationId(), failure));
    }
  }

  /**
   * creates a fully specified scheduler problem statement based on target merlin plan
   *
   * @param planMetadata metadata of the plan container to load from
   * @return a problem specification ready for passing to the scheduler
   */
  private Problem createProblem(final PlanMetadata planMetadata) {
    final var missionModel = loadMissionModel(planMetadata);
    final var problem = new Problem(missionModel, planMetadata.horizon());
    //seed the problem with the initial plan contents
    problem.setInitialPlan(loadInitialPlan(planMetadata, problem));

    //apply constraints/goals to the problem
    loadConstraints(planMetadata, missionModel).forEach(problem::add);
    loadGoals(planMetadata, missionModel).forEach(problem::add);

    return problem;
  }

  /**
   * collects the scheduling goals that apply to the current scheduling run on the target plan
   *
   * @param planMetadata details of the plan container whose associated goals should be collected
   * @param mission the mission model that the plan adheres to, possibly associating additional relevant goals
   * @return the list of goals relevant to the target plan
   * @throws ResultsProtocolFailure when the constraints could not be loaded, or the data stores could not be
   *     reached
   */
  private List<GlobalConstraint> loadConstraints(final PlanMetadata planMetadata, final MissionModel<?> mission) {
    //TODO: is the plan and mission model enough to find the relevant constraints? (eg what about sandbox toggling?)
    //TODO: load global constraints from scheduler data store?
    //TODO: load activity type constraints from somewhere (scheduler store? mission model?)
    //TODO: somehow apply user control over which constraints to enforce during scheduling
    return List.of();
  }

  /**
   * collects the scheduling goals that apply to the current scheduling run on the target plan
   *
   * @param planMetadata details of the plan container whose associated goals should be collected
   * @param missionModel the mission model that the plan adheres to, possibly associating additional relevant goals
   * @return the list of goals relevant to the target plan
   * @throws ResultsProtocolFailure when the goals could not be loaded, or the goal data store could not be reached
   */
  private List<Goal> loadGoals(final PlanMetadata planMetadata, final MissionModel<?> missionModel) {
    //TODO: is the plan and mission model enough to find the relevant goals? (eg what about sandbox goals?)
    //TODO: somehow apply user control over which scheduling rules to actually run vs just check
    //TODO: load scheduling goals from scheduler data store into problem
    try {
      //for v0.10.0, load all hardcoded scheduling goals from a jar into the problem
      final var problems = JarClassLoader.loadProblemsFromJar(this.rulesJarPath.toString(), missionModel);
      return problems.stream().map(Problem::getGoals).flatMap(Collection::stream).collect(Collectors.toList());
    } catch (IOException | ClassNotFoundException | InvocationTargetException | InstantiationException e) {
      //TODO: class-loader related exceptions will not be relevant once interim jar-based rule loading is replaced
      throw new ResultsProtocolFailure(e);
    }
  }

  /**
   * create a scheduler that is tuned to solve the posed problem
   *
   * @param planMetadata details of the plan container that scheduling is occurring from/into
   * @param problem specification of the scheduling problem that needs to be solved
   * @return a new scheduler that is set up to begin providing solutions to the problem
   */
  private Solver createScheduler(final PlanMetadata planMetadata, final Problem problem) {
    final var config = new HuginnConfiguration();
    //TODO: move temporal focus from sched config into Problem object
    //TODO: allow for separate control of windows for constraint analysis vs ability to schedule activities
    //      (eg constraint may need view into immutable past to know how to schedule things in the future)
    config.setHorizon(planMetadata.horizon());
    final var solver = new PrioritySolver(config, problem);
    solver.checkSimBeforeInsertingActInPlan();
    return solver;
  }

  /**
   * load the activity instance content of the specified merlin plan into scheduler-ready objects
   *
   * @param planMetadata metadata of plan container to load from
   * @param problem the problem that the plan adheres to
   * @return a plan with all activity instances loaded from the target merlin plan container
   * @throws ResultsProtocolFailure when the requested plan cannot be loaded, or the target plan revision has
   *     changed, or aerie could not be reached
   */
  private Plan loadInitialPlan(final PlanMetadata planMetadata, final Problem problem) {
    //TODO: maybe paranoid check if plan rev has changed since original metadata?
    try {
      return merlinService.getPlanActivities(planMetadata, problem);
    } catch (Exception e) {
      throw new ResultsProtocolFailure(e);
    }
  }

  /**
   * creates an instance of the mission model referenced by the specified plan
   *
   * @param plan metadata of the target plan indicating which mission model to load and how to configure the mission
   *     model for that plan context
   * @return instance of the mission model to extract any activity types, constraints, and simulations from
   * @throws ResultsProtocolFailure when the mission model could not be loaded: eg jar file not found, declared
   *     version/name in jar does not match, or aerie filesystem could not be mounted
   */
  private MissionModel<?> loadMissionModel(final PlanMetadata plan) {
    try {
      final var missionConfig = SerializedValue.of(plan.modelConfiguration());
      final var modelJarPath = modelJarsDir.resolve(plan.modelPath());

      final var aerieModel = MissionModelLoader.loadMissionModel(
          missionConfig, modelJarPath, plan.modelName(), plan.modelVersion());
      return aerieModel;
    } catch (MissionModelLoader.MissionModelLoadException e) {
      throw new ResultsProtocolFailure(e);
    }
  }

  /**
   * place the modified activity plan back into the target merlin plan container
   *
   * this will obsolete the locally cached planMetadata since the plan revision will change!
   *
   * @param planMetadata metadata of plan container to store into; outdated after return
   * @param newPlan plan with all activity instances that should be stored to target merlin plan container
   * @throws ResultsProtocolFailure when the plan could not be stored to aerie, the target plan revision has
   *     changed, or aerie could not be reached
   */
  private void storeFinalPlan(final PlanMetadata planMetadata, final Plan newPlan) {
    try {
      switch (this.outputMode) {
        case CreateNewOutputPlan -> merlinService.createNewPlanWithActivities(planMetadata, newPlan);
        case UpdateInputPlanWithNewActivities -> merlinService.updatePlanActivities(planMetadata.planId(), newPlan);
        default -> throw new IllegalArgumentException("unsupported scheduler output mode " + this.outputMode);
      }
    } catch (Exception e) {
      throw new ResultsProtocolFailure(e);
    }
  }

  /**
   * collect output summary of the scheduling run
   *
   * depending on service configuration, this result may be cached and served to later requesters
   *
   * only reports one evaluation's score per goal, even if the goal is scored in multiple evaluations
   *
   * @param plan the target plan after the scheduling run has completed
   * @return summary of the state of the plan after scheduling ran; eg goal success metrics, associated instances, etc
   */
  private ScheduleResults collectResults(final Plan plan) {
    final var activityCount = plan.getActivities().size();
    //TODO: complete stub
    return new ScheduleResults(Map.of()); // TODO Adrien: complete this stubbed instance
  }

}
