/*
Stores all of the activities associated with a merge
Gets added to by:
    - taking the diff of the supplier and receiver and uploading all non-conflicting changes with relevant tag
      -  (conflicting ids go into the conflicting activity tables)
    - uploading a resolved conflict with either the tag 'delete' or 'modify' depending on context
      -  (none and add cannot cause conflict)
      -  (a new version of the conflict resolution will replace the version currently in the table
    - deletes are placed as the full activity, but are 'marked to delete' essentially
-- Because of this, to get the full list of activities involved in an in-progress merge requires querying here and conflicting_activities
 */
-- TODO: Consider removing some of the defaults from this table? Decision depends on if we can have an activity
--        that doesn't have a field in this area somehow.
create table merge_staging_area(
    merge_request_id integer
      references merge_request
      on update cascade
      on delete cascade,
    activity_id integer generated by default as identity,

    name text,
    tags text[] default '{}',
    source_scheduling_goal_id integer,
    created_at timestamptz not null,
    start_offset interval not null,
    type text not null,
    arguments merlin_argument_set not null,
    metadata merlin_activity_directive_metadata_set default '{}'::jsonb,

    anchor_id integer default null,
    anchored_to_start boolean default true not null,

    change_type activity_change_type not null,

    primary key (activity_id, merge_request_id)
);

comment on table merge_staging_area is e''
  'The staged version of an activity directive in an in-progress merge to be committed onto the plan receiving changes.';
comment on column merge_staging_area.merge_request_id is e''
  'The merge request associated with this staged activity.\n'
  'Half of the natural key associated with this table, alongside activity_id.';
comment on column merge_staging_area.activity_id is e''
  'The identifier of the staged activity directive.\n'
  'Half of the natural key associated with this table, alongside merge_request_id.';
comment on column merge_staging_area.name is e''
  'The name of this activity directive to be committed.';
comment on column merge_staging_area.tags is e''
  'The tags of this activity directive to be committed.';
comment on column merge_staging_area.source_scheduling_goal_id is e''
  'The id of the scheduling goal that generated this activity directive to be committed.';
comment on column merge_staging_area.created_at is e''
  'The creation time of this activity directive to be committed.';
comment on column merge_staging_area.start_offset is e''
  'The start offset of this activity directive to be committed.';
comment on column merge_staging_area.type is e''
  'The type of this activity directive to be committed.';
comment on column merge_staging_area.arguments is e''
  'The set of arguments to this activity directive to be committed.';
comment on column merge_staging_area.metadata is e''
  'The metadata of this activity directive to be committed.';
comment on column merge_staging_area.anchor_id is e''
  'The identifier of the anchor of this activity directive to be committed.';
comment on column merge_staging_area.anchored_to_start is e''
  'The status of whether this activity directive is anchored to its anchor''s start time to be committed.';
comment on column merge_staging_area.change_type is e''
  'The type of change that has occurred between the version of this activity in the supplying plan'
  ' and the version in the receiving plan, from the perspective of the receiving plan.\n'
  'Can be either "none", "add", "delete", or "modify".';
