java_library(
    name = "merlin-multimission-models",
    srcs = glob(["src/main/java/**/*.java"]),
    extra_arguments = [
        "--source-path", "merlin-multimission-models/src/",
        "--module-path", "third-party/"
        ],
    deps = [
        "//third-party:commons-lang3",
        "//third-party:commons-math3",
        "//third-party:JNISpice",
        "//third-party:junit",

        # Modules
        "//merlin-sdk:merlin-sdk"
    ],
    visibility = ['PUBLIC']
)
